// GanttChartHyperLibraryDemos/Demos/Samples/TypeScript/NetworkDiagramView/Printing/Scripts/DlhSoft.ProjectData.GanttChart.React.Components.js
"use client"

import { useRef, useEffect } from "react";

export function GanttChartView({items, settings, change, style, license, path}) {
    const ganttChartViewRef = useRef(null);

    useEffect(() => {
        const ganttChartView = ganttChartViewRef.current;
        const originalItemPropertyChangeHandler = settings.itemPropertyChangeHandler;
        settings.itemPropertyChangeHandler = (item, propertyName, isDirect, isFinal) => {
            if (originalItemPropertyChangeHandler)
                originalItemPropertyChangeHandler(item, propertyName, isDirect, isFinal);
            if (change)
                change(item, propertyName, isDirect, isFinal);
        };
        DlhSoft.Controls.GanttChartView.initialize(ganttChartView, items, settings, license);
    });

    return (
        <div ref={ganttChartViewRef} style={style}>
            …
            <script src={(path ?? "./") + "DlhSoft.ProjectData.GanttChart.HTML.Controls.js"}/>
            <script src={(path ?? "./") + "DlhSoft.Data.HTML.Controls.js"}/>
            <script src={(path ?? "./") + "DlhSoft.ProjectData.GanttChart.HTML.Controls.Extras.js"}/>
        </div>);
}

export function ScheduleChartView({items, settings, change, style, license, path}) {
    const scheduleChartViewRef = useRef(null);

    useEffect(() => {
        const scheduleChartView = scheduleChartViewRef.current;
        const originalItemPropertyChangeHandler = settings.itemPropertyChangeHandler;
        settings.itemPropertyChangeHandler = (item, propertyName, isDirect, isFinal) => {
            if (originalItemPropertyChangeHandler)
                originalItemPropertyChangeHandler(item, propertyName, isDirect, isFinal);
            if (change)
                change(item, propertyName, isDirect, isFinal);
        };
        DlhSoft.Controls.ScheduleChartView.initialize(scheduleChartView, items, settings, license);
    });

    return (
        <div ref={scheduleChartViewRef} style={style}>
            …
            <script src={(path ?? "./") + "DlhSoft.ProjectData.GanttChart.HTML.Controls.js"}/>
        </div>);
}

export function LoadChartView({items, settings, change, style, license, path}) {
    const loadChartViewRef = useRef(null);

    useEffect(() => {
        const loadChartView = loadChartViewRef.current;
        const originalItemPropertyChangeHandler = settings.itemPropertyChangeHandler;
        settings.itemPropertyChangeHandler = (item, propertyName, isDirect, isFinal) => {
            if (originalItemPropertyChangeHandler)
                originalItemPropertyChangeHandler(item, propertyName, isDirect, isFinal);
            if (change)
                change(item, propertyName, isDirect, isFinal);
        };
        DlhSoft.Controls.LoadChartView.initialize(loadChartView, items, settings, license);
    });

    return (
        <div ref={loadChartViewRef} style={style}>
            …
            <script src={(path ?? "./") + "DlhSoft.ProjectData.GanttChart.HTML.Controls.js"}/>
        </div>);
}

// GanttChartHyperLibraryDemos/Demos/Samples/Angular/LoadChartView/assets/Scripts/DlhSoft.ProjectData.GanttChart.Angular.Components.ts
import { Component, OnInit, ElementRef, Input } from '@angular/core';
import GanttChartItem = DlhSoft.Controls.GanttChartView.Item;
import GanttChartSettings = DlhSoft.Controls.GanttChartView.Settings;
import ScheduleChartItem = DlhSoft.Controls.ScheduleChartView.Item;
import ScheduleChartSettings = DlhSoft.Controls.ScheduleChartView.Settings;
import LoadChartItem = DlhSoft.Controls.LoadChartView.Item;
import LoadChartSettings = DlhSoft.Controls.LoadChartView.Settings;

@Component({
  selector: 'ganttchartview',
  template: '<div><ng-content></ng-content></div>'
})
export class GanttChartView implements OnInit {
  rootElement: HTMLElement;
  @Input() style: string = "";
  @Input() items: GanttChartItem[] = [];
  @Input() settings: GanttChartSettings = {};
  @Input() license: string;
  @Input() change: (item: GanttChartItem, propertyName: string, isDirect: boolean, isFinal: boolean) => void;
  constructor(elementRef: ElementRef) { 
    this.rootElement = <HTMLElement>elementRef.nativeElement;
  }
  ngOnInit() {
    var element = <HTMLElement>this.rootElement.firstChild;
    element.setAttribute('style', this.style);
    var changeHandler = this.settings.itemPropertyChangeHandler;
    DlhSoft.Controls.GanttChartView.initialize(element, this.items, this.settings, this.license);
    if (this.change) {
      this.settings.itemPropertyChangeHandler = (item, propertyName, isDirect, isFinal) => {
        if (changeHandler)
          changeHandler(item, propertyName, isDirect, isFinal);
        this.change(item, propertyName, isDirect, isFinal);
      }
    }
  }
}

@Component({
  selector: 'schedulechartview',
  template: '<div><ng-content></ng-content></div>'
})
export class ScheduleChartView implements OnInit {
  rootElement: HTMLElement;
  @Input() style: string = "";
  @Input() items: ScheduleChartItem[] = [];
  @Input() settings: ScheduleChartSettings = {};
  @Input() license: string;
  @Input() change: (item: GanttChartItem, propertyName: string, isDirect: boolean, isFinal: boolean) => void;
  constructor(elementRef: ElementRef) { 
    this.rootElement = <HTMLElement>elementRef.nativeElement;
  }
  ngOnInit() {
    var element = <HTMLElement>this.rootElement.firstChild;
    element.setAttribute('style', this.style);
    var changeHandler = this.settings.itemPropertyChangeHandler;
    DlhSoft.Controls.ScheduleChartView.initialize(element, this.items, this.settings, this.license);
    if (this.change) {
      this.settings.itemPropertyChangeHandler = (item, propertyName, isDirect, isFinal) => {
        if (changeHandler)
          changeHandler(item, propertyName, isDirect, isFinal);
        this.change(item, propertyName, isDirect, isFinal);
      }
    }
  }
}

@Component({
  selector: 'loadchartview',
  template: '<div><ng-content></ng-content></div>'
})
export class LoadChartView implements OnInit {
  rootElement: HTMLElement;
  @Input() style: string = "";
  @Input() items: LoadChartItem[] = [];
  @Input() settings: LoadChartSettings = {};
  @Input() license: string;
  @Input() change: (item: GanttChartItem, propertyName: string, isDirect: boolean, isFinal: boolean) => void;
  constructor(elementRef: ElementRef) { 
    this.rootElement = <HTMLElement>elementRef.nativeElement;
  }
  ngOnInit() {
    var element = <HTMLElement>this.rootElement.firstChild;
    element.setAttribute('style', this.style);
    var changeHandler = this.settings.itemPropertyChangeHandler;
    DlhSoft.Controls.LoadChartView.initialize(element, this.items, this.settings, this.license);
    if (this.change) {
      this.settings.itemPropertyChangeHandler = (item, propertyName, isDirect, isFinal) => {
        if (changeHandler)
          changeHandler(item, propertyName, isDirect, isFinal);
        this.change(item, propertyName, isDirect, isFinal);
      }
    }
  }
}
