// GanttChartHyperLibraryDemos/Demos/Samples/React/LoadChartView/MainFeatures/app.jsx
var loadChartView;
class App extends React.Component {
    constructor(props) {
        super(props);
        this.loadChartViewRef = React.createRef();
    }
    componentDidMount() {
        loadChartView = this.loadChartViewRef.current;
    }
    render() {
        // Query string syntax: ?theme
        // Supported themes: Default, Generic-bright, Generic-blue, DlhSoft-gray, Purple-green, Steel-blue, Dark-black, Cyan-green, Blue-navy, Orange-brown, Teal-green, Purple-beige, Gray-blue, Aero.
        var queryString = window.location.search;
        var theme = queryString ? queryString.substr(1) : null;

        var date = new Date(), year = date.getFullYear(), month = date.getMonth();
        var loadChartItems = [{
            content: 'Resource 1', ganttChartItems: [{ content: 'Task 1 (Resource 1)', start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 2, 16, 0, 0) },
            { content: 'Task 1, Task 2 [50%] (Resource 1): 150%', start: new Date(year, month, 3, 8, 0, 0), finish: new Date(year, month, 3, 12, 0, 0), units: 1.5 },
            { content: 'Task 2 [50%] (Resource 1)', start: new Date(year, month, 3, 12, 0, 0), finish: new Date(year, month, 4, 16, 0, 0), units: 0.5 },
            { content: 'Task 3 (Resource 1)', start: new Date(year, month, 6, 8, 0, 0), finish: new Date(year, month, 6, 16, 0, 0) }]},
            { content: 'Resource 2', ganttChartItems: [{ content: 'Task 2 (Resource 2)', start: new Date(year, month, 3, 8, 0, 0), finish: new Date(year, month, 4, 16, 0, 0) }] }];

        for (var i = 3; i <= 16; i++)
            loadChartItems.push({
                content: 'Resource ' + i, ganttChartItems: [{ content: 'Task X (Resource ' + i + ')', start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 5, 16, 0, 0) },
                { content: 'Task Y (Resource ' + i + ')', start: new Date(year, month, 7, 8, 0, 0), finish: new Date(year, month, 8, 16, 0, 0) }]
            });

        var settings = {
            // Set the current time value to automatically scroll to a specific chart coordinate, and display a vertical bar highlighter at the specified point.
            currentTime: new Date(year, month, 2, 12, 0, 0)
        };

        // Optionally, initialize custom themes (themes.js).
        initializeLoadChartTheme(settings, theme);

        function onItemChanged(item, propertyName, isDirect, isFinal) {
            if (!isDirect || !isFinal) // Skip internal changes, and changes occurred during drag operations.
                return;
            console.log(propertyName + ' changed for ' + item.content + '.');
        }
        function moveItemUp() {
            if (loadChartView.selectedItem == null)
                return;
            var item = loadChartView.selectedItem;
            loadChartView.moveLoadChartItemUp(item);
            loadChartView.scrollToItem(item);
        }
        function moveItemDown() {
            if (loadChartView.selectedItem == null)
                return;
            var item = loadChartView.selectedItem;
            loadChartView.moveLoadChartItemDown(item);
            loadChartView.scrollToItem(item);
        }
        function increaseTimelinePage() {
            loadChartView.increaseTimelinePage(4 * 7 * 24 * 60 * 60 * 1000); // 4 weeks
        }
        function decreaseTimelinePage() {
            loadChartView.decreaseTimelinePage(4 * 7 * 24 * 60 * 60 * 1000); // 4 weeks
        }
        function setCustomScales() {
            settings.headerHeight = 21 * 3;
            settings.scales = [{ scaleType: 'NonworkingTime', isHeaderVisible: false, isHighlightingVisible: true, highlightingStyle: 'stroke-width: 0; fill: #f8f8f8; fill-opacity: 0.65' },
            { scaleType: 'Months', headerTextFormat: 'Month', headerStyle: 'padding: 2.25px; border-right: solid 1px White; border-bottom: solid 1px White; color: gray; white-space: nowrap; overflow: hidden; text-overflow: ellipsis', isSeparatorVisible: true, separatorStyle: 'stroke: #c8bfe7; stroke-width: 0.5px' },
            { scaleType: 'Weeks', headerTextFormat: 'Date', headerStyle: 'padding: 2.25px; border-right: solid 1px White; border-bottom: solid 1px White; color: gray', isSeparatorVisible: true, separatorStyle: 'stroke: #c8bfe7; stroke-width: 0.5px' },
            { scaleType: 'Days', headerTextFormat: 'Day', headerStyle: 'padding: 2.25px; border-right: solid 1px White; color: gray' },
            { scaleType: 'CurrentTime', isHeaderVisible: false, isSeparatorVisible: true, separatorStyle: 'stroke: #e31d3b; stroke-width: 0.5px' }];
            settings.updateScale = 60 * 60 * 1000; // 1 hour
            settings.hourWidth = 5;
            settings.visibleWeekStart = 1; // Monday
            settings.visibleWeekFinish = 5; // Friday
            settings.workingWeekStart = 1; // Monday
            settings.workingWeekFinish = 4; // Thursday
            settings.visibleDayStart = 10 * 60 * 60 * 1000; // 10 AM
            settings.visibleDayFinish = 20 * 60 * 60 * 1000; // 8 PM
            settings.specialNonworkingDays = [new Date(year, month, 24), new Date(year, month, 25)];
            loadChartView.refresh();
        }
        function zoomIn() {
            loadChartView.setHourWidth(settings.hourWidth * 2);
        }
        function print() {
            // Print the task hierarchy column and a selected timeline page of 5 weeks (timeline end week extensions would be added automatically, if necessary).
            // Optionally, to rotate the print output and simulate Landscape printing mode (when the end user keeps Portrait selection in the Print dialog), append the rotate parameter set to true to the method call: rotate: true.
            loadChartView.print({ title: 'Load Chart (printable)', isGridVisible: true, columnIndexes: [0], timelineStart: new Date(year, month, 1), timelineFinish: new Date(new Date(year, month, 1).valueOf() + 5 * 7 * 24 * 60 * 60 * 1000), preparingMessage: '...' });
        }
        return (
            <div>
                <div className="ribbonContainer">
                    <div className="ribbonPanel">
                        <div className="ribbonHeader">Items</div>
                        <div className="ribbonCommandsArea">
                            <div className="ribbonCommand"><a href="#" onClick={moveItemUp} title="Move selected item up"><img src="Images/MoveUp.png" alt="Move up" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={moveItemDown} title="Move selected item down"><img src="Images/MoveDown.png" alt="Move down" /></a></div>
                        </div>
                    </div>
                    <div className="ribbonPanel">
                        <div className="ribbonHeader">Timeline/Schedule</div>
                        <div className="ribbonCommandsArea">
                            <div className="ribbonCommand"><a href="#" onClick={setCustomScales} title="Set custom scales"><img src="Images/CustomScales.png" alt="Custom scales" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={zoomIn} title="Zoom in"><img src="Images/ZoomIn.png" alt="Zoom in" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={decreaseTimelinePage} title="Move towards past"><img src="Images/DecreaseTimelinePage.png" alt="Decrease timeline page" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={increaseTimelinePage} title="Move towards future"><img src="Images/IncreaseTimelinePage.png" alt="Increase timeline page" /></a></div>
                        </div>
                    </div>
                    <div className="ribbonPanel">
                        <div className="ribbonHeader">Printing</div>
                        <div className="ribbonCommandsArea">
                            <div className="ribbonCommand"><a href="#" onClick={print} title="Print"><img src="Images/Print.png" alt="Print" /></a></div>
                        </div>
                    </div>
                </div>
                <LoadChartView ref={this.loadChartViewRef} items={loadChartItems} settings={settings} change={onItemChanged} style={{ minHeight: '388px' }}>...</LoadChartView>
            </div>);
    }
}

// GanttChartHyperLibraryDemos/Demos/Samples/Angular/LoadChartView/MainFeatures/Project/src/app/app.component.ts
import { Component, Output, OnInit, ViewChild, ElementRef } from '@angular/core';
import LoadChartView = DlhSoft.Controls.LoadChartView;
import LoadChartItem = LoadChartView.Item;
import LoadChartSettings = LoadChartView.Settings;

declare var initializeLoadChartTheme: any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'Angular-LoadChartViewSampleApp';

  @ViewChild('loadChartView', { read: ElementRef, static: true }) loadChartViewRef: ElementRef;
  loadChartView: LoadChartView.Element; 

  items: LoadChartItem[];
  settings: LoadChartSettings;
  onItemChanged: (item: LoadChartItem, propertyName: string, isDirect: boolean, isFinal: boolean) => void;
  setCustomBarColorToItem: () => void;
  moveItemUp: () => void;
  moveItemDown: () => void;
  setCustomScales: () => void;
  zoomIn: () => void;
  decreaseTimelinePage: () => void;
  increaseTimelinePage: () => void;
  print: () => void;

  // Query string syntax: ?theme
// Supported themes: Default, Generic-bright, Generic-blue, DlhSoft-gray, Purple-green, Steel-blue, Dark-black, Cyan-green, Blue-navy, Orange-brown, Teal-green, Purple-beige, Gray-blue, Aero.
  queryString = window.location.search;
  theme = this.queryString ? this.queryString.substr(1) : null;
  
  constructor() {
    var date = new Date(), year = date.getFullYear(), month = date.getMonth();
    var loadChartItems = <LoadChartItem[]>[{
          content: 'Resource 1', ganttChartItems: [{ content: 'Task 1 (Resource 1)', start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 2, 16, 0, 0) },
            { content: 'Task 1, Task 2 [50%] (Resource 1): 150%', start: new Date(year, month, 3, 8, 0, 0), finish: new Date(year, month, 3, 12, 0, 0), units: 1.5 },
            { content: 'Task 2 [50%] (Resource 1)', start: new Date(year, month, 3, 12, 0, 0), finish: new Date(year, month, 4, 16, 0, 0), units: 0.5 },
            { content: 'Task 3 (Resource 1)', start: new Date(year, month, 6, 8, 0, 0), finish: new Date(year, month, 6, 16, 0, 0) }] },
          { content: 'Resource 2', ganttChartItems: [{ content: 'Task 2 (Resource 2)', start: new Date(year, month, 3, 8, 0, 0), finish: new Date(year, month, 4, 16, 0, 0) }] }];
    for (var i = 3; i <= 16; i++)
      loadChartItems.push(<LoadChartItem>{
        content: 'Resource ' + i, ganttChartItems: [{ content: 'Task X (Resource ' + i + ')', start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 5, 16, 0, 0) },
          { content: 'Task Y (Resource ' + i + ')', start: new Date(year, month, 7, 8, 0, 0), finish: new Date(year, month, 8, 16, 0, 0) }] });

    this.items = loadChartItems;

    var settings = <LoadChartSettings>{
      // Set the current time value to automatically scroll to a specific chart coordinate, and display a vertical bar highlighter at the specified point.
      currentTime: new Date(year, month, 2, 12, 0, 0)
    };

    this.settings = settings;

    this.onItemChanged = (item, propertyName, isDirect, isFinal) => {
      if (!isDirect || !isFinal) // Skip internal changes, and changes occurred during drag operations.
        return;
      console.log(propertyName + ' changed for ' + item.content + '.');
    }

    this.setCustomBarColorToItem = () => {
      if (this.loadChartView.loadChartItems.length <= 1)
        return;
      var LoadChartItem = this.loadChartView.loadChartItems[1];
      if (LoadChartItem.ganttChartItems.length <= 2)
        return;
      var item = LoadChartItem.ganttChartItems[2];
      item.barStyle = 'stroke: Green; fill: LightGreen';
      item.completedBarStyle = 'stroke: Gray; fill: Gray';
      this.loadChartView.refreshChartItem(item);
      this.loadChartView.scrollToItem(LoadChartItem);
    }
    this.moveItemUp = () => {
      if (this.loadChartView.getSelectedItem() == null)
        return;
      var item = this.loadChartView.getSelectedItem();
      this.loadChartView.moveLoadChartItemUp(item);
      this.loadChartView.scrollToItem(item);
    }
    this.moveItemDown = () => {
      if (this.loadChartView.getSelectedItem() == null)
        return;
      var item = this.loadChartView.getSelectedItem();
      this.loadChartView.moveLoadChartItemDown(item);
      this.loadChartView.scrollToItem(item);
    }
    this.setCustomScales = () => {
      this.settings.headerHeight = 21 * 3;
      this.settings.scales = [{ scaleType: 'NonworkingTime', isHeaderVisible: false, isHighlightingVisible: true, highlightingStyle: 'stroke-width: 0; fill: #f8f8f8; fill-opacity: 0.65' },
        { scaleType: 'Months', headerTextFormat: 'Month', headerStyle: 'padding: 2.25px; border-right: solid 1px White; border-bottom: solid 1px White; color: gray; white-space: nowrap; overflow: hidden; text-overflow: ellipsis', isSeparatorVisible: true, separatorStyle: 'stroke: #c8bfe7; stroke-width: 0.5px' },
        { scaleType: 'Weeks', headerTextFormat: 'Date', headerStyle: 'padding: 2.25px; border-right: solid 1px White; border-bottom: solid 1px White; color: gray', isSeparatorVisible: true, separatorStyle: 'stroke: #c8bfe7; stroke-width: 0.5px' },
        { scaleType: 'Days', headerTextFormat: 'Day', headerStyle: 'padding: 2.25px; border-right: solid 1px White; color: gray' },
        { scaleType: 'CurrentTime', isHeaderVisible: false, isSeparatorVisible: true, separatorStyle: 'stroke: #e31d3b; stroke-width: 0.5px' }];
      this.settings.updateScale = 60 * 60 * 1000; // 1 hour
      this.settings.hourWidth = 5;
      this.settings.visibleWeekStart = 1; // Monday
      this.settings.visibleWeekFinish = 5; // Friday
      this.settings.workingWeekStart = 1; // Monday
      this.settings.workingWeekFinish = 4; // Thursday
      this.settings.visibleDayStart = 10 * 60 * 60 * 1000; // 10 AM
      this.settings.visibleDayFinish = 20 * 60 * 60 * 1000; // 8 PM
      this.settings.specialNonworkingDays = [new Date(year, month, 24), new Date(year, month, 25)];
      this.loadChartView.refresh();
    }
    this.zoomIn = () => {
      this.settings.hourWidth *= 2;
      this.loadChartView.refresh();
    }
    this.increaseTimelinePage = () => {
      this.loadChartView.increaseTimelinePage(4 * 7 * 24 * 60 * 60 * 1000); // 4 weeks
    }
    this.decreaseTimelinePage = () => {
      this.loadChartView.decreaseTimelinePage(4 * 7 * 24 * 60 * 60 * 1000); // 4 weeks
    }
    this.print = () => {
      // Print the resource list column and a selected timeline page of 5 weeks (timeline end week extensions would be added automatically, if necessary).
      this.loadChartView.print({ title: 'Load Chart (printable)', isGridVisible: true, columnIndexes: [0], timelineStart: new Date(year, month, 1), timelineFinish: new Date(new Date(year, month, 1).valueOf() + 5 * 7 * 24 * 60 * 60 * 1000), preparingMessage: '...' });
    }
  }

  ngOnInit() {
    this.loadChartView = <LoadChartView.Element>(<HTMLElement>this.loadChartViewRef.nativeElement).firstChild;

    // Optionally, initialize custom themes (themes.js).
    initializeLoadChartTheme(this.settings, this.theme);
  }
}


<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content below * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * Delete the template below * * * * * * * * * * -->
<!-- * * * * * * * to get started with your project! * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

<style>
  :host {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    font-size: 14px;
    color: #333;
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    margin: 8px 0;
  }

  p {
    margin: 0;
  }

  .spacer {
    flex: 1;
  }

  .toolbar {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 60px;
    display: flex;
    align-items: center;
    background-color: #1976d2;
    color: white;
    font-weight: 600;
  }

  .toolbar img {
    margin: 0 16px;
  }

  .toolbar #twitter-logo {
    height: 40px;
    margin: 0 8px;
  }

  .toolbar #youtube-logo {
    height: 40px;
    margin: 0 16px;
  }

  .toolbar #twitter-logo:hover,
  .toolbar #youtube-logo:hover {
    opacity: 0.8;
  }

  .content {
    display: flex;
    margin: 82px auto 32px;
    padding: 0 16px;
    max-width: 960px;
    flex-direction: column;
    align-items: center;
  }

  svg.material-icons {
    height: 24px;
    width: auto;
  }

  svg.material-icons:not(:last-child) {
    margin-right: 8px;
  }

  .card svg.material-icons path {
    fill: #888;
  }

  .card-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    margin-top: 16px;
  }

  .card {
    all: unset;
    border-radius: 4px;
    border: 1px solid #eee;
    background-color: #fafafa;
    height: 40px;
    width: 200px;
    margin: 0 8px 16px;
    padding: 16px;
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    transition: all 0.2s ease-in-out;
    line-height: 24px;
  }

  .card-container .card:not(:last-child) {
    margin-right: 0;
  }

  .card.card-small {
    height: 16px;
    width: 168px;
  }

  .card-container .card:not(.highlight-card) {
    cursor: pointer;
  }

  .card-container .card:not(.highlight-card):hover {
    transform: translateY(-3px);
    box-shadow: 0 4px 17px rgba(0, 0, 0, 0.35);
  }

  .card-container .card:not(.highlight-card):hover .material-icons path {
    fill: rgb(105, 103, 103);
  }

  .card.highlight-card {
    background-color: #1976d2;
    color: white;
    font-weight: 600;
    border: none;
    width: auto;
    min-width: 30%;
    position: relative;
  }

  .card.card.highlight-card span {
    margin-left: 60px;
  }

  svg#rocket {
    width: 80px;
    position: absolute;
    left: -10px;
    top: -24px;
  }

  svg#rocket-smoke {
    height: calc(100vh - 95px);
    position: absolute;
    top: 10px;
    right: 180px;
    z-index: -10;
  }

  a,
  a:visited,
  a:hover {
    color: #1976d2;
    text-decoration: none;
  }

  a:hover {
    color: #125699;
  }

  .terminal {
    position: relative;
    width: 80%;
    max-width: 600px;
    border-radius: 6px;
    padding-top: 45px;
    margin-top: 8px;
    overflow: hidden;
    background-color: rgb(15, 15, 16);
  }

  .terminal::before {
    content: "\2022 \2022 \2022";
    position: absolute;
    top: 0;
    left: 0;
    height: 4px;
    background: rgb(58, 58, 58);
    color: #c2c3c4;
    width: 100%;
    font-size: 2rem;
    line-height: 0;
    padding: 14px 0;
    text-indent: 4px;
  }

  .terminal pre {
    font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
    color: white;
    padding: 0 1rem 1rem;
    margin: 0;
  }

  .circle-link {
    height: 40px;
    width: 40px;
    border-radius: 40px;
    margin: 8px;
    background-color: white;
    border: 1px solid #eeeeee;
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
    transition: 1s ease-out;
  }

  .circle-link:hover {
    transform: translateY(-0.25rem);
    box-shadow: 0px 3px 15px rgba(0, 0, 0, 0.2);
  }

  footer {
    margin-top: 8px;
    display: flex;
    align-items: center;
    line-height: 20px;
  }

  footer a {
    display: flex;
    align-items: center;
  }

  .github-star-badge {
    color: #24292e;
    display: flex;
    align-items: center;
    font-size: 12px;
    padding: 3px 10px;
    border: 1px solid rgba(27,31,35,.2);
    border-radius: 3px;
    background-image: linear-gradient(-180deg,#fafbfc,#eff3f6 90%);
    margin-left: 4px;
    font-weight: 600;
  }

  .github-star-badge:hover {
    background-image: linear-gradient(-180deg,#f0f3f6,#e6ebf1 90%);
    border-color: rgba(27,31,35,.35);
    background-position: -.5em;
  }

  .github-star-badge .material-icons {
    height: 16px;
    width: 16px;
    margin-right: 4px;
  }

  svg#clouds {
    position: fixed;
    bottom: -160px;
    left: -230px;
    z-index: -10;
    width: 1920px;
  }

  /* Responsive Styles */
  @media screen and (max-width: 767px) {
    .card-container > *:not(.circle-link) ,
    .terminal {
      width: 100%;
    }

    .card:not(.highlight-card) {
      height: 16px;
      margin: 8px 0;
    }

    .card.highlight-card span {
      margin-left: 72px;
    }

    svg#rocket-smoke {
      right: 120px;
      transform: rotate(-5deg);
    }
  }

  @media screen and (max-width: 575px) {
    svg#rocket-smoke {
      display: none;
      visibility: hidden;
    }
  }
</style>

<h1>LoadChartView sample</h1>
<div class="ribbonContainer">
  <div class="ribbonPanel">
    <div class="ribbonHeader">Items</div>
    <div class="ribbonCommandsArea">
      <div class="ribbonCommand"><a href="javascript://" (click)="moveItemUp()" title="Move selected item up"><img src="assets/images/MoveUp.png" alt="Move up" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="moveItemDown()" title="Move selected item down"><img src="assets/images/MoveDown.png" alt="Move down" /></a></div>
    </div>
  </div>
  <div class="ribbonPanel">
    <div class="ribbonHeader">Timeline/Schedule</div>
    <div class="ribbonCommandsArea">
      <div class="ribbonCommand"><a href="javascript://" (click)="setCustomScales()" title="Set custom scales"><img src="assets/images/CustomScales.png" alt="Custom scales" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="zoomIn()" title="Zoom in"><img src="assets/images/ZoomIn.png" alt="Zoom in" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="decreaseTimelinePage()" title="Move towards past"><img src="assets/images/DecreaseTimelinePage.png" alt="Decrease timeline page" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="increaseTimelinePage()" title="Move towards future"><img src="assets/images/IncreaseTimelinePage.png" alt="Increase timeline page" /></a></div>
    </div>
  </div>
  <div class="ribbonPanel">
    <div class="ribbonHeader">Printing</div>
    <div class="ribbonCommandsArea">
      <div class="ribbonCommand"><a href="javascript://" (click)="print()" title="Print"><img src="assets/images/Print.png" alt="Print" /></a></div>
    </div>
  </div>
</div>
<!-- Load Chart component. -->
<loadchartview #loadChartView [items]="items" [settings]="settings" [change]="onItemChanged" style="min-height: 388px">...</loadchartview>
