// GanttChartHyperLibraryDemos/Demos/Samples/React/GanttChartView/PredecessorsSuccessors/app.jsx
var ganttChartView;
class App extends React.Component {
    constructor(props) {
        super(props);
        this.ganttChartViewRef = React.createRef();
    }
    componentDidMount() {
        ganttChartView = this.ganttChartViewRef.current;
    }
    render() {
        // Query string syntax: ?theme
        // Supported themes: Default, Generic-bright, Generic-blue, Royal-blue, DlhSoft-gray, Purple-green, Steel-blue, Dark-black, Cyan-green, Blue-navy, Orange-brown, Teal-green, Purple-beige, Gray-blue, Aero.
        var queryString = window.location.search;
        var theme = queryString ? queryString.substr(1) : null;

        var date = new Date(), year = date.getFullYear(), month = date.getMonth();
        var items = [{ content: 'Planning', label: 'Planning', isExpanded: false },
            { content: 'Analysis', indentation: 1, start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 3, 16, 0, 0), assignmentsContent: 'Clarissa Candelaria [50%]' },
            { content: 'Requirements', indentation: 1, start: new Date(year, month, 3, 8, 0, 0), finish: new Date(year, month, 4, 16, 0, 0), assignmentsContent: 'Clarissa Candelaria  [50%], Tyson Lamberson' },
            { content: 'Review', label: 'Review', indentation: 1, start: new Date(year, month, 2, 16, 0, 0), isMilestone: true, assignmentsContent: 'Clarissa Candelaria' },
            { content: 'Arhitecture', indentation: 1, start: new Date(year, month, 4, 8, 0, 0), finish: new Date(year, month, 6, 12, 0, 0), assignmentsContent: 'Steven Rush [50%], Meeting room' },
            { content: 'Design', indentation: 1, start: new Date(year, month, 6, 10, 0, 0), finish: new Date(year, month, 8, 12, 0, 0), assignmentsContent: 'Steven Rush [50%]' },
            { content: 'Development', label: 'Development', isExpanded: true },
            { content: 'Start development', label: 'Start development', indentation: 1, start: new Date(year, month, 4, 8, 0, 0), isMilestone: true, assignmentsContent: 'Steven Rush' },
            { content: 'Date-times', indentation: 1, start: new Date(year, month, 4, 8, 0, 0), finish: new Date(year, month, 7, 12, 0, 0), completedFinish: new Date(year, month, 5, 12, 0, 0), assignmentsContent: 'Joanna Mcamis' },
            { content: 'Schedules', indentation: 1, start: new Date(year, month, 4, 8, 0, 0), finish: new Date(year, month, 7, 12, 0, 0), completedFinish: new Date(year, month, 5, 12, 0, 0), assignmentsContent: 'Clarissa Candelaria, Steven Rush [50%]' },
            { content: 'Automation testing functions', label: 'Very important!', indentation: 1, start: new Date(year, month, 4, 8, 0, 0), finish: new Date(year, month, 12, 12, 0, 0), assignmentsContent: 'Tyson Lamberson [50%]' },
            { content: 'Chart', label: 'Chart', indentation: 1 },
            { content: 'Bars', indentation: 2, start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 5, 16, 0, 0), completedFinish: new Date(year, month, 7, 16, 0, 0), assignmentsContent: 'Clarissa Candelaria [50%]' },
            { content: 'Summary bars', indentation: 2, start: new Date(year, month, 6, 8, 0, 0), finish: new Date(year, month, 9, 16, 0, 0), assignmentsContent: 'Steven Rush [50%]' },
            { content: 'Review', indentation: 2, start: new Date(year, month, 9, 16, 0, 0), isMilestone: true },
            { content: 'Links', indentation: 2, start: new Date(year, month, 7, 8, 0, 0), finish: new Date(year, month, 10, 16, 0, 0), assignmentsContent: 'Steven Rush [50%]' },
            { content: 'Diagram functions', indentation: 2, start: new Date(year, month, 5, 8, 0, 0), finish: new Date(year, month, 8, 12, 0, 0), assignmentsContent: 'Tyson Lamberson [50%]' },
            { content: 'Quality assurance', label: 'Very important!', start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 17, 16, 0, 0), hasMilestoneAtFinish: true, assignmentsContent: 'Denis Kaelin, Printer' },
            { content: 'Project delivery', start: new Date(year, month, 10, 8, 0, 0), finish: new Date(year, month, 12, 12, 0, 0), assignmentsContent: 'Clarissa Candelaria, Meeting room' },
            { content: 'Maintenance', start: new Date(year, month, 12, 12, 0, 0), finish: new Date(year, month, 18, 12, 0, 0) },
            { content: 'Marketing', label: 'Marketing', start: new Date(year, month, 10, 12, 0, 0), finish: new Date(year, month, 15, 12, 0, 0) },
            { content: 'Preparations', indentation: 1, start: new Date(year, month, 10, 8, 0, 0), isMilestone: true, assignmentsContent: 'Joanna Mcamis, Alicia Rock' },
            { content: 'Colors', indentation: 1, start: new Date(year, month, 11, 8, 0, 0), finish: new Date(year, month, 14, 12, 0, 0), assignmentsContent: 'Joanna Mcamis [25%]' },
            { content: 'Logo', indentation: 1, start: new Date(year, month, 11, 8, 0, 0), finish: new Date(year, month, 14, 12, 0, 0), assignmentsContent: 'Alicia Rock [25%]' },
            { content: 'Samples app', indentation: 1, start: new Date(year, month, 11, 8, 0, 0), finish: new Date(year, month, 16, 12, 0, 0), assignmentsContent: 'Clarissa Candelaria' },
            { content: 'Screenshots', indentation: 1, start: new Date(year, month, 12, 8, 0, 0), finish: new Date(year, month, 15, 16, 0, 0), assignmentsContent: 'Joanna Mcamis' },
            { content: 'Videos', indentation: 1, start: new Date(year, month, 15, 8, 0, 0), finish: new Date(year, month, 18, 16, 0, 0), assignmentsContent: 'Alicia Rock [50%]' }
            ];
        items[3].predecessors = [{ item: items[0], dependencyType: 'SS' }];
        items[7].predecessors = [{ item: items[6], lag: 2 * 60 * 60 * 1000 }];
        items[8].predecessors = [{ item: items[4] }, { item: items[5] }];
        items[9].finish.setDate(items[9].finish.getDate() + 2);
        items[10].predecessors = [{ item: items[9] }];

        var settings = {
            // Auto-scheduling is initially turned on.
            areTaskDependencyConstraintsEnabled: true,
            // Set the current time value to automatically scroll to a specific chart coordinate, and display a vertical bar highlighter at the specified point.
            currentTime: new Date(year, month, 2, 12, 0, 0)
        };

        var columns = DlhSoft.Controls.GanttChartView.getDefaultColumns(items, settings);
        var indexOffset = columns[0].isSelection ? 1 : 0;

        columns.splice(3 + indexOffset, 0, {
            header: 'Predecessors', width: 200, cellTemplate: (item) => {
                return DlhSoft.Controls.GanttChartView.multiSelectorComboBoxInputColumnTemplateBase(
                    document, 196,
                    () => { return items.filter((i) => !ganttChartView.itemDependsOf(i, item)).map((i) => i.content.replaceAll(',', '')); },
                    () => { return item.predecessors ? item.predecessors.map((p) => p.item.content.replaceAll(',', '')).join(', ') : '' },
                    (value) => {
                        let allValues = items.map((i) => i.content.replaceAll(',', ''));
                        let values = value.split(',').map((v) => v.trim());
                        let predecessorsString = values.filter((v) => allValues.indexOf(v) >= 0).map((v) => allValues.indexOf(v)).join(', ');
                        ganttChartView.setItemPredecessorsString(item, predecessorsString, true);
                        if (item.predecessors) {
                            for (let predecessorItem of item.predecessors) {
                                ganttChartView.refreshItem(predecessorItem.item);
                            }
                        }
                        ganttChartView.refreshItemNeighbourhood(item);
                    }
                )
            }
        });

        columns.splice(4 + indexOffset, 0, {
            header: 'Successors', width: 200, cellTemplate: (item) => {
                return DlhSoft.Controls.GanttChartView.multiSelectorComboBoxInputColumnTemplateBase(
                    document, 196,
                    () => { return items.filter((i) => !ganttChartView.itemDependsOf(item, i)).map((i) => i.content.replaceAll(',', '')); },
                    () => { return ganttChartView.getItemSuccessors(item).map((s) => s.content.replaceAll(',', '')).join(', ') },
                    (value) => {
                        let allValues = items.map((i) => i.content.replaceAll(',', ''));
                        let values = value.split(',').map((v) => v.trim()).filter((v) => allValues.indexOf(v) >= 0);
                        let successors = ganttChartView.getItemSuccessors(item);
                        let index = items.indexOf(item);
                        for (successor of successors) {
                            if (values.indexOf(successor.content) < 0) {
                                let predecessorsString = ', ' + ganttChartView.getItemPredecessorsString(successor) + ',';
                                predecessorsString = predecessorsString.replace(', ' + (index + 1) + ',', ',');
                                ganttChartView.setItemPredecessorsString(successor, predecessorsString);
                                ganttChartView.refreshItemNeighbourhood(successor);
                            }
                        }
                        for (value of values) {
                            let successor = items[allValues.indexOf(value)];
                            let predecessorsString = ', ' + ganttChartView.getItemPredecessorsString(successor) + ',';
                            if (predecessorsString.indexOf(', ' + (index + 1) + ',') < 0) {
                                predecessorsString = predecessorsString + (index + 1);
                                ganttChartView.setItemPredecessorsString(successor, predecessorsString);
                                ganttChartView.refreshItemNeighbourhood(successor);
                            }
                        }
                        ganttChartView.refreshItemNeighbourhood(item);
                    }
                )
            }
        });

        settings.itemPropertyChangeHandler = function (item, propertyName, isDirect, isFinal) {
            if (isDirect && isFinal && propertyName == 'content') {
                ganttChartView.refreshItemNeighbourhood(item);
                for (var successor of ganttChartView.getItemSuccessors(item))
                    ganttChartView.refreshItem(successor);
            }
        };
        settings.columns = columns;
        // Optionally, define assignable resources.
        settings.assignableResources = ['Clarissa Candelaria', 'Tyson Lamberson', 'Steven Rush',
            'Joanna Mcamis', 'Denis Kaelin', 'Alicia Rock',
            'Meeting room', 'Printer'];
        settings.autoAppendAssignableResources = true;

        initializeGanttChartTheme(settings, theme);

        function onItemChanged(item, propertyName, isDirect, isFinal) {
            if (!isDirect || !isFinal) // Skip internal changes, and changes occurred during drag operations.
                return;
            console.log(propertyName + ' changed for ' + item.content + '.');
        }
        return (
            <div>
                <GanttChartView ref={this.ganttChartViewRef} items={items} settings={settings} change={onItemChanged} style={{ minHeight: '388px' }}>...</GanttChartView>
            </div>);
    }
}

// GanttChartHyperLibraryDemos/Demos/Samples/Angular/GanttChartView/BuiltinScales/app.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import GanttChartView = DlhSoft.Controls.GanttChartView;
import GanttChartItem = GanttChartView.Item;
import GanttChartSettings = GanttChartView.Settings;
import PredecessorItem = GanttChartView.PredecessorItem;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'Angular-Scss-GanttChartViewSample';

  @ViewChild('ganttChartView', { read: ElementRef, static: true }) ganttChartViewRef: ElementRef;
  ganttChartView: GanttChartView.Element; 

  items: GanttChartItem[];
  settings: GanttChartSettings;
  license = '…'; // upon purchasing a product license from DlhSoft
  onItemChanged: (item: GanttChartItem, propertyName: string, isDirect: boolean, isFinal: boolean) => void;
  scaleType = "Weeks";
  onScaleChanged: () => void;

  constructor() {
    var date = new Date(), year = date.getFullYear(), month = date.getMonth();
    var items = <GanttChartItem[]>[{ content: 'Planning', label: 'Planning', isExpanded: false },
      { content: 'Analysis', indentation: 1, start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 3, 16, 0, 0), assignmentsContent: 'Clarissa Candelaria [50%]' },
      { content: 'Requirements', indentation: 1, start: new Date(year, month, 3, 8, 0, 0), finish: new Date(year, month, 4, 16, 0, 0), assignmentsContent: 'Clarissa Candelaria  [50%], Tyson Lamberson' },
      { content: 'Review', label: 'Review', indentation: 1, start: new Date(year, month, 2, 16, 0, 0), isMilestone: true, assignmentsContent: 'Clarissa Candelaria' },
      { content: 'Arhitecture', indentation: 1, start: new Date(year, month, 4, 8, 0, 0), finish: new Date(year, month, 6, 12, 0, 0), assignmentsContent: 'Steven Rush [50%], Meeting room' },
      { content: 'Design', indentation: 1, start: new Date(year, month, 6, 10, 0, 0), finish: new Date(year, month, 8, 12, 0, 0), assignmentsContent: 'Steven Rush [50%]' },
      { content: 'Development', label: 'Development', isExpanded: true },
      { content: 'Start development', label: 'Start development', indentation: 1, start: new Date(year, month, 4, 8, 0, 0), isMilestone: true, assignmentsContent: 'Steven Rush' },
      { content: 'Date-times', indentation: 1, start: new Date(year, month, 4, 8, 0, 0), finish: new Date(year, month, 7, 12, 0, 0), completedFinish: new Date(year, month, 5, 12, 0, 0), assignmentsContent: 'Joanna Mcamis' },
      { content: 'Schedules', indentation: 1, start: new Date(year, month, 4, 8, 0, 0), finish: new Date(year, month, 7, 12, 0, 0), completedFinish: new Date(year, month, 5, 12, 0, 0), assignmentsContent: 'Clarissa Candelaria, Steven Rush [50%]' },
      { content: 'Automation testing functions', label: 'Very important!', indentation: 1, start: new Date(year, month, 4, 8, 0, 0), finish: new Date(year, month, 12, 12, 0, 0), assignmentsContent: 'Tyson Lamberson [50%]' },
      { content: 'Chart', label: 'Chart', indentation: 1 },
      { content: 'Bars', indentation: 2, start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 5, 16, 0, 0), completedFinish: new Date(year, month, 7, 16, 0, 0), assignmentsContent: 'Clarissa Candelaria [50%]' },
      { content: 'Summary bars', indentation: 2, start: new Date(year, month, 6, 8, 0, 0), finish: new Date(year, month, 9, 16, 0, 0), assignmentsContent: 'Steven Rush [50%]' },
      { content: 'Review', indentation: 2, start: new Date(year, month, 9, 16, 0, 0), isMilestone: true },
      { content: 'Links', indentation: 2, start: new Date(year, month, 7, 8, 0, 0), finish: new Date(year, month, 10, 16, 0, 0), assignmentsContent: 'Steven Rush [50%]' },
      { content: 'Diagram functions', indentation: 2, start: new Date(year, month, 5, 8, 0, 0), finish: new Date(year, month, 8, 12, 0, 0), assignmentsContent: 'Tyson Lamberson [50%]' },
      { content: 'Quality assurance', label: 'Very important!', start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 17, 16, 0, 0), hasMilestoneAtFinish: true, assignmentsContent: 'Denis Kaelin, Printer' },
      { content: 'Project delivery', start: new Date(year, month, 10, 8, 0, 0), finish: new Date(year, month, 12, 12, 0, 0), assignmentsContent: 'Clarissa Candelaria, Meeting room' },
      { content: 'Maintenance', start: new Date(year, month, 12, 12, 0, 0), finish: new Date(year, month, 18, 12, 0, 0) },
      { content: 'Marketing', label: 'Marketing', start: new Date(year, month, 10, 12, 0, 0), finish: new Date(year, month, 15, 12, 0, 0) },
      { content: 'Preparations', indentation: 1, start: new Date(year, month, 10, 8, 0, 0), isMilestone: true, assignmentsContent: 'Joanna Mcamis, Alicia Rock' },
      { content: 'Colors', indentation: 1, start: new Date(year, month, 11, 8, 0, 0), finish: new Date(year, month, 14, 12, 0, 0), assignmentsContent: 'Joanna Mcamis [25%]' },
      { content: 'Logo', indentation: 1, start: new Date(year, month, 11, 8, 0, 0), finish: new Date(year, month, 14, 12, 0, 0), assignmentsContent: 'Alicia Rock [25%]' },
      { content: 'Samples app', indentation: 1, start: new Date(year, month, 11, 8, 0, 0), finish: new Date(year, month, 16, 12, 0, 0), assignmentsContent: 'Clarissa Candelaria' },
      { content: 'Screenshots', indentation: 1, start: new Date(year, month, 12, 8, 0, 0), finish: new Date(year, month, 15, 16, 0, 0), assignmentsContent: 'Joanna Mcamis' },
      { content: 'Videos', indentation: 1, start: new Date(year, month, 15, 8, 0, 0), finish: new Date(year, month, 18, 16, 0, 0), assignmentsContent: 'Alicia Rock [50%]' }];

    items[6].predecessors = <PredecessorItem[]>[{ item: items[0], dependencyType: 'StartStart' }];
    items[4].predecessors = <PredecessorItem[]>[{ item: items[2], lag: 2 * 60 * 60 * 1000 }];
    items[8].predecessors = <PredecessorItem[]>[{ item: items[4] }, { item: items[5] }];
    items[9].assignmentsContent = 'Clarissa Candelaria';
    items[10].predecessors = <PredecessorItem[]>[{ item: items[9] }];
    this.items = items;

    this.settings = { 
      containerClass: 'container',
      standardItemClass: 'task',
      milestoneItemClass: 'milestone',
      summaryBarClass: 'summaryBar',
      standardBarClass: 'standardBar',
      standardCompletedBarClass: 'standardCompletedBar',
      milestoneBarClass: 'milestoneBar',
      dependencyLineClass: 'dependencyLine',
      assignmentsClass: 'assignments',
      arrowFill: '#f1c232',
      currentTime: new Date(year, month, 2, 12, 0, 0)
    };
    this.onItemChanged = (item, propertyName, isDirect, isFinal) => {
      console.log(propertyName + ' changed for ' + item.content + '.');
    }
    this.onScaleChanged = () => {
      this.settings.scales[1].scaleType = this.scaleType;
      switch (this.scaleType) {
        case 'Years':
          this.settings.scales[1].headerTextFormat = 'Year';
          this.settings.scales[2].scaleType = 'Months';
          this.settings.scales[2].headerTextFormat = 'Month';
          this.settings.hourWidth = 1;
          break;
        case 'Months':
          this.settings.scales[1].headerTextFormat = 'MonthYear';
          this.settings.scales[2].scaleType = 'Weeks';
          this.settings.scales[2].headerTextFormat = 'Date';
          this.settings.hourWidth = 2.5;
          break;
        case 'Weeks':
          this.settings.scales[1].headerTextFormat = 'Date';
          this.settings.scales[2].scaleType = 'Days';
          this.settings.scales[2].headerTextFormat = 'DayOfWeekAbbreviation';
          this.settings.hourWidth = 5;
          break;
        case 'Days':
          this.settings.scales[1].headerTextFormat = 'Date';
          this.settings.scales[2].scaleType = 'Hours';
          this.settings.scales[2].headerTextFormat = 'Hour';
          this.settings.hourWidth = 25;
          break;
        }
      this.ganttChartView.refresh();
    }
  }

  ngOnInit() {
    this.ganttChartView = <GanttChartView.Element>(<HTMLElement>this.ganttChartViewRef.nativeElement).firstChild;
  }
}
