// GanttChartHyperLibraryDemos/Demos/Samples/React/PertChartView/MainFeatures/app.jsx
var pertChartView;
class App extends React.Component {
    constructor(props) {
        super(props);
        this.pertChartViewRef = React.createRef();
    }
    componentDidMount() {
        pertChartView = this.pertChartViewRef.current;
    }
    render() {
        // Query string syntax: ?theme
        // Supported themes: Default, Generic-bright, Generic-blue, Blue-green, Royal-blue, DlhSoft-gray, Purple-green, Steel-blue, Dark-black, Cyan-green, Blue-navy, Orange-brown, Teal-green, Purple-beige, Gray-blue, Aero.
        var queryString = window.location.search;
        var theme = queryString ? queryString.substr(1) : null;

        // Prepare data items.
        var secondDuration = 1000, minuteDuration = 60 * secondDuration, hourDuration = 60 * minuteDuration;
        var items = [{ displayedText: '0', content: 'Start' },
                     { displayedText: '1', content: 'Task event 1' },
                     { displayedText: '2', content: 'Task event 2' },
                     { displayedText: '3', content: 'Task event 3' },
                     { displayedText: '4', content: 'Finish', displayedRowIndex: 0 }];
        items[1].predecessors = [{ item: items[0], displayedText: 'A', content: 'Task A', effort: 4 * hourDuration }];
        items[2].predecessors = [{ item: items[0], displayedText: 'B', content: 'Task B', effort: 2 * hourDuration }];
        items[3].predecessors = [{ item: items[2], displayedText: 'C', content: 'Task C', effort: 1 * hourDuration }];
        items[4].predecessors = [{ item: items[1], displayedText: 'D', content: 'Task D', effort: 5 * hourDuration },
                                 { item: items[2], displayedText: 'E', content: 'Task E', effort: 3 * hourDuration },
                                 { item: items[3], displayedText: 'F', content: 'Task F', effort: 2 * hourDuration }];

        var settings = {  };

        // Optionally, initialize custom themes (themes.js).
        initializePertChartTheme(settings, theme);

        function setCustomBarColorToItem() {
            var item = pertChartView.items[2];
            item.shapeStyle = 'stroke: DarkMagenta; fill: LightYellow';
            pertChartView.refreshItem(item);
        }
        function setCustomDependencyLineColorToPredecessorItem() {
            var item = pertChartView.items[2];
            var predecessorItem = pertChartView.items[2].predecessors[0];
            predecessorItem.dependencyLineStyle = 'stroke: DarkMagenta; fill: none; marker-end: url(#ArrowMarker)';
            pertChartView.refreshPredecessorItems(item);
        }
        function highlightCriticalPath() {
            var i, j;
            for (i = 0; i < pertChartView.items.length; i++) {
                var item = pertChartView.items[i];
                delete item.shapeStyle;
                if (item.predecessors) {
                    for (j = 0; j < item.predecessors.length; j++)
                        delete item.predecessors[j].dependencyLineStyle;
                }
            }
            var criticalDependencies = pertChartView.getCriticalDependencies();
            for (i = 0; i < criticalDependencies.length; i++) {
                var predecessorItem = criticalDependencies[i];
                predecessorItem.dependencyLineStyle = 'stroke: Red; fill: none: none; marker-end: url(#ArrowMarker)';
                predecessorItem.item.shapeStyle = 'stroke: Red; fill: White';
                if (i >= criticalDependencies.length - 1) {
                    for (var p in predecessorItem)
                        predecessorItem.dependentItem.shapeStyle = 'stroke: Red; fill: White';
                }
            }

            pertChartView.refreshChartItems();
        }
        function print() {
            pertChartView.print({ title: 'PERT Chart (printable)', preparingMessage: '...' });
        }
        return (
            <div>
                <div className="ribbonContainer">
                    <div className="ribbonPanel">
                        <div className="ribbonHeader">Items</div>
                        <div className="ribbonCommandsArea">
                            <div className="ribbonCommand"><a href="#" onClick={setCustomBarColorToItem} title="Set custom bar color to Task event 2"><img src="Images/SetColor.png" alt="Set color" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={setCustomDependencyLineColorToPredecessorItem} title="Set custom dependency line color to Task B"><img src="Images/SetDependencyColor.png" alt="Set custom dependency" /></a></div>
                        </div>
                    </div>
                    <div className="ribbonPanel">
                        <div className="ribbonHeader">Project tools</div>
                        <div className="ribbonCommandsArea">
                            <div className="ribbonCommand"><a href="#" onClick={highlightCriticalPath} title="Highlight critical path"><img src="Images/CriticalPath.png" alt="Critical path" /></a></div>
                        </div>
                    </div>
                    <div className="ribbonPanel">
                        <div className="ribbonHeader">Printing</div>
                        <div className="ribbonCommandsArea">
                            <div className="ribbonCommand"><a href="#" onClick={print} title="Print"><img src="Images/Print.png" alt="Print" /></a></div>
                        </div>
                    </div>
                </div>
                <PertChartView ref={this.pertChartViewRef} items={items} settings={settings} style={{ minHeight: '388px' }}>...</PertChartView>
            </div>);
    }
}

// GanttChartHyperLibraryDemos/Demos/Samples/Angular/PertChartView/MainFeatures/Project/src/app/app.component.ts
import { Component, Output, OnInit, ViewChild, ElementRef } from '@angular/core';
import PertChartView = DlhSoft.Controls.Pert.PertChartView;
import PertChartItem = PertChartView.Item;
import PertChartSettings = PertChartView.Settings;
import PredecessorItem = PertChartView.PredecessorItem;

declare var initializePertChartTheme: any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'Angular-PertChartViewSampleApp';

  @ViewChild('pertChartView', { read: ElementRef, static: true }) pertChartViewRef: ElementRef;
  pertChartView: PertChartView.Element; 

  items: PertChartItem[];
  settings: PertChartSettings;
  onItemChanged: (item: PertChartItem, propertyName: string, isDirect: boolean, isFinal: boolean) => void;
  setCustomBarColorToItem: () => void;
  setCustomDependencyLineColorToPredecessorItem: () => void;
  highlightCriticalPath: () => void;
  print: () => void;

  // Query string syntax: ?theme
// Supported themes: Default, Generic-bright, Generic-blue, Royal-blue, DlhSoft-gray, Purple-green, Steel-blue, Dark-black, Cyan-green, Blue-navy, Orange-brown, Teal-green, Purple-beige, Gray-blue, Aero.
  queryString = window.location.search;
  theme = this.queryString ? this.queryString.substr(1) : null;
  
  constructor() {
    var secondDuration = 1000, minuteDuration = 60 * secondDuration, hourDuration = 60 * minuteDuration;
    var items = <PertChartItem[]>[{ displayedText: '0', content: 'Start' },
                 { displayedText: '1', content: 'Task event 1' },
                 { displayedText: '2', content: 'Task event 2' },
                 { displayedText: '3', content: 'Task event 3' },
                 { displayedText: '4', content: 'Finish', displayedRowIndex: 0 }];
    items[1].predecessors = <PredecessorItem[]>[{ item: items[0], displayedText: 'A', content: 'Task A', effort: 4 * hourDuration }];
    items[2].predecessors = <PredecessorItem[]>[{ item: items[0], displayedText: 'B', content: 'Task B', effort: 2 * hourDuration }];
    items[3].predecessors = <PredecessorItem[]>[{ item: items[2], displayedText: 'C', content: 'Task C', effort: 1 * hourDuration }];
    items[4].predecessors = <PredecessorItem[]>[{ item: items[1], displayedText: 'D', content: 'Task D', effort: 5 * hourDuration },
                                                { item: items[2], displayedText: 'E', content: 'Task E', effort: 3 * hourDuration },
                                                { item: items[3], displayedText: 'F', content: 'Task F', effort: 2 * hourDuration }];

    this.items = items;

    var settings = <PertChartSettings>{ };

    this.settings = settings;

    this.onItemChanged = (item, propertyName, isDirect, isFinal) => {
      if (!isDirect || !isFinal) // Skip internal changes, and changes occurred during drag operations.
        return;
      console.log(propertyName + ' changed for ' + item.content + '.');
    }

    this.setCustomBarColorToItem = () => {
      var item = this.pertChartView.items[2];
      item.shapeStyle = 'stroke: DarkMagenta; fill: LightYellow';
      this.pertChartView.refreshItem(item);
    }
    this.setCustomDependencyLineColorToPredecessorItem = () => {
      var item = this.pertChartView.items[2];
      var predecessorItem = this.pertChartView.items[2].predecessors[0];
      predecessorItem.dependencyLineStyle = 'stroke: DarkMagenta; fill: none; marker-end: url(#' + (this.theme != 'Default' ? 'Pert' : '') + 'ArrowMarker)';
      this.pertChartView.refreshPredecessorItems(item);
    }
    this.highlightCriticalPath = () => {
      var i, j;
      for (i = 0; i < this.pertChartView.items.length; i++) {
        var item = this.pertChartView.items[i];
        delete item.shapeStyle;
        if (item.predecessors) {
          for (j = 0; j < item.predecessors.length; j++)
            delete item.predecessors[j].dependencyLineStyle;
        }
      }
      var criticalDependencies = this.pertChartView.getCriticalDependencies();
      for (i = 0; i < criticalDependencies.length; i++) {
        var predecessorItem = criticalDependencies[i];
        predecessorItem.dependencyLineStyle = 'stroke: Red; fill: none: none; marker-end: url(#' + (this.theme != 'Default' ? 'Pert' : '') + 'ArrowMarker)';
        predecessorItem.item.shapeStyle = 'stroke: Red; fill: White';
        if (i >= criticalDependencies.length - 1)
          predecessorItem["dependentItem"].shapeStyle = 'stroke: Red; fill: White';
      }
      this.pertChartView.refreshItems();
    }
    this.print = () => {
      this.pertChartView.print({ title: 'PERT Chart (printable)', preparingMessage: '...' });
    }
  }

  ngOnInit() {
    this.pertChartView = <PertChartView.Element>(<HTMLElement>this.pertChartViewRef.nativeElement).firstChild;

    // Optionally, initialize custom themes (themes.js).
    initializePertChartTheme(this.settings, this.theme);
  }
}


<style>
  :host {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    font-size: 14px;
    color: #333;
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    margin: 8px 0;
  }

  p {
    margin: 0;
  }

  .spacer {
    flex: 1;
  }

  .toolbar {
    height: 60px;
    margin: -8px;
    display: flex;
    align-items: center;
    background-color: #1976d2;
    color: white;
    font-weight: 600;
  }

    .toolbar img {
      margin: 0 16px;
    }

    .toolbar #twitter-logo {
      height: 40px;
      margin: 0 16px;
    }

      .toolbar #twitter-logo:hover {
        opacity: 0.8;
      }

  .content {
    display: flex;
    margin: 32px auto;
    padding: 0 16px;
    max-width: 960px;
    flex-direction: column;
    align-items: center;
  }

  svg.material-icons {
    height: 24px;
    width: auto;
  }

    svg.material-icons:not(:last-child) {
      margin-right: 8px;
    }

  .card svg.material-icons path {
    fill: #888;
  }

  .card-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    margin-top: 16px;
  }

  .card {
    border-radius: 4px;
    border: 1px solid #eee;
    background-color: #fafafa;
    height: 40px;
    width: 200px;
    margin: 0 8px 16px;
    padding: 16px;
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    transition: all 0.2s ease-in-out;
    line-height: 24px;
  }

  .card-container .card:not(:last-child) {
    margin-right: 0;
  }

  .card.card-small {
    height: 16px;
    width: 168px;
  }

  .card-container .card:not(.highlight-card) {
    cursor: pointer;
  }

    .card-container .card:not(.highlight-card):hover {
      transform: translateY(-3px);
      box-shadow: 0 4px 17px rgba(black, 0.35);
    }

      .card-container .card:not(.highlight-card):hover .material-icons path {
        fill: rgb(105, 103, 103);
      }

  .card.highlight-card {
    background-color: #1976d2;
    color: white;
    font-weight: 600;
    border: none;
    width: auto;
    min-width: 30%;
    position: relative;
  }

  .card.card.highlight-card span {
    margin-left: 60px;
  }

  svg#rocket {
    width: 80px;
    position: absolute;
    left: -10px;
    top: -24px;
  }

  svg#rocket-smoke {
    height: 100vh;
    position: absolute;
    top: 10px;
    right: 180px;
    z-index: -10;
  }

  a,
  a:visited,
  a:hover {
    color: #1976d2;
    text-decoration: none;
  }

    a:hover {
      color: #125699;
    }

  .terminal {
    position: relative;
    width: 80%;
    max-width: 600px;
    border-radius: 6px;
    padding-top: 45px;
    margin-top: 8px;
    overflow: hidden;
    background-color: rgb(15, 15, 16);
  }

    .terminal::before {
      content: "\2022 \2022 \2022";
      position: absolute;
      top: 0;
      left: 0;
      height: 4px;
      background: rgb(58, 58, 58);
      color: #c2c3c4;
      width: 100%;
      font-size: 2rem;
      line-height: 0;
      padding: 14px 0;
      text-indent: 4px;
    }

    .terminal pre {
      font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
      color: white;
      padding: 0 1rem 1rem;
      margin: 0;
    }

  .circle-link {
    height: 40px;
    width: 40px;
    border-radius: 40px;
    margin: 8px;
    background-color: white;
    border: 1px solid #eeeeee;
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
    transition: 1s ease-out;
  }

    .circle-link:hover {
      transform: translateY(-0.25rem);
      box-shadow: 0px 3px 15px rgba(0, 0, 0, 0.2);
    }

  footer {
    margin-top: 8px;
    display: flex;
    align-items: center;
    line-height: 20px;
  }

    footer a {
      display: flex;
      align-items: center;
    }

  .github-star-badge {
    color: #24292e;
    display: flex;
    align-items: center;
    font-size: 12px;
    padding: 3px 10px;
    border: 1px solid rgba(27,31,35,.2);
    border-radius: 3px;
    background-image: linear-gradient(-180deg,#fafbfc,#eff3f6 90%);
    margin-left: 4px;
    font-weight: 600;
    font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;
  }

    .github-star-badge:hover {
      background-image: linear-gradient(-180deg,#f0f3f6,#e6ebf1 90%);
      border-color: rgba(27,31,35,.35);
      background-position: -.5em;
    }

    .github-star-badge .material-icons {
      height: 16px;
      width: 16px;
      margin-right: 4px;
    }

  svg#clouds {
    position: fixed;
    bottom: -160px;
    left: -230px;
    z-index: -10;
    width: 1920px;
  }


  /* Responsive Styles */
  @media screen and (max-width: 767px) {

    .card-container > *:not(.circle-link),
    .terminal {
      width: 100%;
    }

    .card:not(.highlight-card) {
      height: 16px;
      margin: 8px 0;
    }

    .card.highlight-card span {
      margin-left: 72px;
    }

    svg#rocket-smoke {
      right: 120px;
      transform: rotate(-5deg);
    }
  }

  @media screen and (max-width: 575px) {
    svg#rocket-smoke {
      display: none;
      visibility: hidden;
    }
  }
</style>

<h1>PertChartView sample</h1>
<div class="ribbonContainer">
  <div class="ribbonPanel">
    <div class="ribbonHeader">Items</div>
    <div class="ribbonCommandsArea">
      <div class="ribbonCommand"><a href="javascript://" (click)="setCustomBarColorToItem()" title="Set custom bar color to selected item"><img src="assets/images/SetColor.png" alt="Set color" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="setCustomDependencyLineColorToPredecessorItem()" title="Set custom dependency line color to Task B"><img src="assets/images/SetDependencyColor.png" alt="Set dependency color" /></a></div>
    </div>
  </div>
  <div class="ribbonPanel">
    <div class="ribbonHeader">Project tools</div>
    <div class="ribbonCommandsArea">
      <div class="ribbonCommand"><a href="javascript://" (click)="highlightCriticalPath()" title="Highlight critical path"><img src="assets/images/CriticalPath.png" alt="Critical path" /></a></div>
    </div>
  </div>
  <div class="ribbonPanel">
    <div class="ribbonHeader">Printing</div>
    <div class="ribbonCommandsArea">
      <div class="ribbonCommand"><a href="javascript://" (click)="print()" title="Print"><img src="assets/images/Print.png" alt="Print" /></a></div>
    </div>
  </div>
</div>
<!-- Pert Chart component. -->
<pertchartview #pertChartView [items]="items" [settings]="settings" [change]="onItemChanged" style="min-height: 388px">...</pertchartview>
