// GanttChartHyperLibraryDemos/Demos/Samples/Angular/GanttChartView/MainFeatures/Project/src/app/app.component.ts
import { Component, Output, OnInit, ViewChild, ElementRef } from '@angular/core';
import GanttChartView = DlhSoft.Controls.GanttChartView;
import GanttChartItem = GanttChartView.Item;
import GanttChartSettings = GanttChartView.Settings;
import PredecessorItem = GanttChartView.PredecessorItem;

declare var initializeGanttChartTheme: any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'Angular-GanttChartViewSampleApp';

  @ViewChild('ganttChartView', { read: ElementRef, static: true }) ganttChartViewRef: ElementRef;
  ganttChartView: GanttChartView.Element; 

  items: GanttChartItem[];
  settings: GanttChartSettings;
  onItemChanged: (item: GanttChartItem, propertyName: string, isDirect: boolean, isFinal: boolean) => void;
  addNewItem: () => void;
  insertNewItem: () => void;
  editItem: () => void;
  decreaseItemIndentation: () => void;
  increaseItemIndentation: () => void;
  deleteItem: () => void;
  setCustomBarColorToItem: () => void;
  copyItem: () => void;
  pasteItem: () => void;
  moveItemUp: () => void;
  moveItemDown: () => void;
  setCustomScales: () => void;
  zoomIn: () => void;
  decreaseTimelinePage: () => void;
  increaseTimelinePage: () => void;
  toggleBaseline: () => void;
  highlightCriticalPath: () => void;
  splitRemainingWork: () => void;
  toggleDependencyConstraints: () => void;
  levelResources: () => void;
  print: () => void;

  isBaselineVisible: boolean;
  isHighlightCriticalPathVisible: boolean;
  isDependencyConstraintsActive: boolean;

  // Query string syntax: ?theme
// Supported themes: Default, Generic-bright, Generic-blue, Royal-blue, DlhSoft-gray, Purple-green, Steel-blue, Dark-black, Cyan-green, Blue-navy, Orange-brown, Teal-green, Purple-beige, Gray-blue, Aero.
  queryString = window.location.search;
  theme = this.queryString ? this.queryString.substr(1) : null;
  
  constructor() {
    var date = new Date(), year = date.getFullYear(), month = date.getMonth();
    var items = <GanttChartItem[]>[
      { content: 'Task 1', isExpanded: false, start: date },
      { content: 'Task 1.1', indentation: 1, start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 4, 16, 0, 0) },
      { content: 'Task 1.2', indentation: 1, start: new Date(year, month, 3, 8, 0, 0), finish: new Date(year, month, 5, 12, 0, 0) },
      { content: 'Task 2', isExpanded: true, start: date },
      { content: 'Task 2.1', indentation: 1, start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 8, 16, 0, 0), completedFinish: new Date(year, month, 5, 16, 0, 0), assignmentsContent: 'Resource 1, Resource 2 [50%]' },
      { content: 'Task 2.2', indentation: 1, start: date},
      { content: 'Task 2.2.1', indentation: 2, start: new Date(year, month, 11, 8, 0, 0), finish: new Date(year, month, 14, 16, 0, 0), completedFinish: new Date(year, month, 14, 16, 0, 0), assignmentsContent: 'Resource 2' },
      { content: 'Task 2.2.2', indentation: 2, start: new Date(year, month, 12, 12, 0, 0), finish: new Date(year, month, 14, 16, 0, 0), assignmentsContent: 'Resource 2' },
      { content: 'Task 3', indentation: 1, start: new Date(year, month, 15, 16, 0, 0), isMilestone: true },
      { content: 'Task 4', indentation: 1, start: new Date(year, month, 15, 16, 0, 0), finish: new Date(year, month, 18, 16, 0, 0) },
      { content: 'Task 5', indentation: 1, start: new Date(year, month, 16, 16, 0, 0), finish: new Date(year, month, 17, 16, 0, 0) }];

    items[2].predecessors = <PredecessorItem[]>[{ item: items[1] }]; // Task 2 depends on Task 1.
    items[7].predecessors = <PredecessorItem[]>[{ item: items[6], dependencyType: 'StartStart' }]; // Task 6 depends on Task 5 using Start-Start dependency type.
    items[8].predecessors = <PredecessorItem[]>[{ item: items[0] }, { item: items[3] }]; // Milestone depends on Story A and Story B.

    this.items = items;

    var settings = <GanttChartSettings>{
      // Auto-scheduling is initially turned on.
      areTaskDependencyConstraintsEnabled: true,

      // Set the current time value to automatically scroll to a specific chart coordinate, and display a vertical bar highlighter at the specified point.
      currentTime: new Date(year, month, 2, 12, 0, 0)
    };

    // Optionally, set baseline properties.
    items[6].baselineStart = new Date(year, month, 10, 8, 0, 0);
    items[6].baselineFinish = new Date(year, month, 11, 16, 0, 0);
    items[7].baselineStart = new Date(year, month, 8, 8, 0, 0);
    items[7].baselineFinish = new Date(year, month, 11, 16, 0, 0);
    items[8].baselineStart = new Date(year, month, 12, 8, 0, 0);

    // Customize columns.
    var columns = GanttChartView.getDefaultColumns(items, settings);
    var indexOffset = columns[0].isSelection ? 1 : 0;
    columns.splice(0 + indexOffset, 0, { header: '', width: 40, cellTemplate: GanttChartView.getIndexColumnTemplate() });
    columns.splice(3 + indexOffset, 0, { header: 'Effort (h)', width: 80, cellTemplate: GanttChartView.getTotalEffortColumnTemplate(64) });
    columns.splice(4 + indexOffset, 0, { header: 'Duration (d)', width: 80, cellTemplate: GanttChartView.getDurationColumnTemplate(64, 8) });
    columns.splice(8 + indexOffset, 0, { header: '%', width: 80, cellTemplate: GanttChartView.getCompletionColumnTemplate(64) });
    columns.splice(9 + indexOffset, 0, { header: 'Predecessors', width: 100, cellTemplate: GanttChartView.getPredecessorsColumnTemplate(84) });
    columns.push({ header: 'Cost ($)', width: 100, cellTemplate: GanttChartView.getCostColumnTemplate(84) });
    columns.push({ header: 'Est. start', width: 140, cellTemplate: GanttChartView.getBaselineStartColumnTemplate(124, true, true, 8 * 60 * 60 * 1000) }); // 8 AM
    columns.push({ header: 'Est. finish', width: 140, cellTemplate: GanttChartView.getBaselineFinishColumnTemplate(124, true, true, 16 * 60 * 60 * 1000) }); // 4 PM
    settings.columns = columns;

    // Optionally, define assignable resources.
    settings.assignableResources = [
      'Resource 1', 'Resource 2', 'Resource 3',
      'Material 1', 'Material 2'];
    //settings.autoAppendAssignableResources = true;
    // Optionally, define the quantity values to consider when leveling resources, indicating maximum material amounts available for use at the same time.
    settings.resourceQuantities = [{ key: 'Material 1', value: 4 }, { key: 'Material 2', value: Infinity }];
    items[9].assignmentsContent = 'Material 1 [250%], Material 2';
    items[10].assignmentsContent = 'Material 1, Material 2 [200%]';
    // Optionally, define task and resource costs.
    settings.taskInitiationCost = 5;
    items[4].executionCost = 50;
    settings.defaultResourceUsageCost = 1;
    settings.specificResourceUsageCosts = [{ key: 'Resource 1', value: 2 }, { key: 'Material 1', value: 7}];
    settings.defaultResourceHourCost = 10;
    settings.specificResourceHourCosts = [{ key: 'Resource 1', value: 20 }, { key: 'Material 2', value: 0.5 }];

    this.settings = settings;
    this.settings.isBaselineVisible = true;
    this.isBaselineVisible = settings.isBaselineVisible;
    this.isHighlightCriticalPathVisible = false;
    this.isDependencyConstraintsActive = settings.areTaskDependencyConstraintsEnabled;

    this.onItemChanged = (item, propertyName, isDirect, isFinal) => {
      if (!isDirect || !isFinal) // Skip internal changes, and changes occurred during drag operations.
        return;
      console.log(propertyName + ' changed for ' + item.content + '.');
    }

    this.addNewItem = () => {
      var item = <GanttChartItem>{ content: 'New task', start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 4, 16, 0, 0) };
      this.ganttChartView.addItem(item);
      this.ganttChartView.selectItem(item);
      this.ganttChartView.scrollToItem(item);
      this.ganttChartView.scrollToDateTime(new Date(year, month, 1));
    }
    this.insertNewItem = () => {
      if (this.ganttChartView.getSelectedItem() == null)
        return;
      var item = <GanttChartItem>{ content: 'New task', start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 4, 16, 0, 0) };
      this.ganttChartView.insertItem(this.ganttChartView.getSelectedItem().index, item);
      this.ganttChartView.selectItem(item);
      this.ganttChartView.scrollToItem(item);
      this.ganttChartView.scrollToDateTime(new Date(year, month, 1));
    }
    this.increaseItemIndentation = () => {
      var item = this.ganttChartView.getSelectedItem();
      if (item == null)
        return;
      this.ganttChartView.increaseItemIndentation(item);
      this.ganttChartView.scrollToItem(item);
    }
    this.decreaseItemIndentation = () => {
      var item = this.ganttChartView.getSelectedItem();
      if (item == null)
        return;
      this.ganttChartView.decreaseItemIndentation(item);
      this.ganttChartView.scrollToItem(item);
    }
    this.deleteItem = () => {
      var item = this.ganttChartView.getSelectedItem();
      if (item == null)
        return;
      this.ganttChartView.removeItem(item);
    }
    this.setCustomBarColorToItem = () => {
      var item = this.ganttChartView.getSelectedItem();
      if (item == null)
        return;
      item.barStyle = 'stroke: Green; fill: LightGreen';
      item.completedBarStyle = 'stroke: Gray; fill: Gray';
      this.ganttChartView.refreshChartItem(item);
    }
    var copiedItem;
    this.copyItem = () => {
      var item = this.ganttChartView.getSelectedItem();
      if (item == null)
        return;
      copiedItem = item;
    }
    this.pasteItem = () => {
      var selectedItem = this.ganttChartView.getSelectedItem();
      if (copiedItem == null || selectedItem == null)
        return;
      var item = <GanttChartItem>{ content: copiedItem.content, start: copiedItem.start, finish: copiedItem.finish, completedFinish: copiedItem.completedFinish, isMilestone: copiedItem.isMilestone, assignmentsContent: copiedItem.assignmentsContent, isRelativeToTimezone: copiedItem.isRelativeToTimezone };
      this.ganttChartView.insertItem(selectedItem.index + 1, item);
      this.ganttChartView.selectItem(item);
      this.ganttChartView.scrollToItem(item);
      this.ganttChartView.scrollToDateTime(item.start);
    }
    this.moveItemUp = () => {
      var item = this.ganttChartView.getSelectedItem();
      if (item == null)
        return;
      this.ganttChartView.moveItemHierarchyUp(item);
      this.ganttChartView.scrollToItem(item);
    }
    this.moveItemDown = () => {
      var item = this.ganttChartView.getSelectedItem();
      if (item == null)
        return;
      this.ganttChartView.moveItemHierarchyDown(item);
      this.ganttChartView.scrollToItem(item);
    }
    this.setCustomScales = () => {
      settings.headerHeight = 21 * 3;
      settings.scales = [
        { scaleType: 'NonworkingTime', isHeaderVisible: false, isHighlightingVisible: true, highlightingStyle: 'stroke-width: 0; fill: #f8f8f8; fill-opacity: 0.65' },
        { scaleType: 'Months', headerTextFormat: 'Month', headerStyle: 'padding: 2.25px; border-right: solid 1px White; border-bottom: solid 1px White; color: gray', isSeparatorVisible: true, separatorStyle: 'stroke: #c8bfe7; stroke-width: 0.5px' },
        { scaleType: 'Weeks', headerTextFormat: 'Date', headerStyle: 'padding: 2.25px; border-right: solid 1px White; border-bottom: solid 1px White; color: gray', isSeparatorVisible: true, separatorStyle: 'stroke: #c8bfe7; stroke-width: 0.5px' },
        { scaleType: 'Days', headerTextFormat: 'Day', headerStyle: 'padding: 2.25px; border-right: solid 1px White; color: gray' },
        { scaleType: 'CurrentTime', isHeaderVisible: false, isSeparatorVisible: true, separatorStyle: 'stroke: #e31d3b; stroke-width: 0.5px' }];
      settings.updateScale = 60 * 60 * 1000; // 1 hour
      settings.hourWidth = 5;
      settings.visibleWeekStart = 1; // Monday
      settings.visibleWeekFinish = 5; // Friday
      settings.workingWeekStart = 1; // Monday
      settings.workingWeekFinish = 4; // Thursday
      settings.visibleDayStart = 10 * 60 * 60 * 1000; // 10 AM
      settings.visibleDayFinish = 20 * 60 * 60 * 1000; // 8 PM
      settings.specialNonworkingDays = [new Date(year, month, 24), new Date(year, month, 25)];
      this.ganttChartView.refresh();
    }
    this.zoomIn = () => {
      this.ganttChartView.setHourWidth(settings.hourWidth * 2);
    }
    this.increaseTimelinePage = () => {
      this.ganttChartView.increaseTimelinePage(4 * 7 * 24 * 60 * 60 * 1000); // 4 weeks
    }
    this.decreaseTimelinePage = () => {
      this.ganttChartView.decreaseTimelinePage(4 * 7 * 24 * 60 * 60 * 1000); // 4 weeks
    }
    this.toggleBaseline = () => {
      settings.isBaselineVisible = !settings.isBaselineVisible;
      this.isBaselineVisible = settings.isBaselineVisible;
      this.ganttChartView.refresh();
    }
    this.highlightCriticalPath = () => {
      for (var i = 0; i < this.ganttChartView.items.length; i++) {
        var item = this.ganttChartView.items[i];
        delete item.barStyle;
        if (!item.hasChildren && this.ganttChartView.isItemCritical(item))
          item.barStyle = 'stroke: #e31d3b; fill: #e31d3b';
        this.ganttChartView.refreshChartItem(item);
        this.isHighlightCriticalPathVisible = true;
      }
    }
    this.splitRemainingWork = () => {
      var item = this.ganttChartView.getSelectedItem();
      if (item == null)
        return;
      var remainingWorkItem = this.ganttChartView.splitRemainingWork(item);
      if (remainingWorkItem == null)
        return;
    }
    this.toggleDependencyConstraints = () => {
      settings.areTaskDependencyConstraintsEnabled = !settings.areTaskDependencyConstraintsEnabled;
      this.isDependencyConstraintsActive = settings.areTaskDependencyConstraintsEnabled;
      this.ganttChartView.refresh();
    }
    this.levelResources = () => {
      // Level the assigned resources for all tasks, including the already started ones, considering the current time displayed in the chart.
      this.ganttChartView.levelResources(true, this.ganttChartView.settings.currentTime);
    // Alternatively, optimize work to obtain the minimum project finish date and time assuming unlimited resource availability:
    // ganttChartView.optimizeWork(false, true, ganttChartView.settings.currentTime);
    }
    this.print = () => {
      // Print the task hierarchy column and a selected timeline page of 5 weeks (timeline end week extensions would be added automatically, if necessary).
      // Optionally, to rotate the print output and simulate Landscape printing mode (when the end user keeps Portrait selection in the Print dialog), append the rotate parameter set to true to the method call: rotate: true.
      this.ganttChartView.print({ title: 'Gantt Chart (printable)', isGridVisible: true, columnIndexes: [1], timelineStart: new Date(year, month, 1), timelineFinish: new Date(new Date(year, month, 1).valueOf() + 5 * 7 * 24 * 60 * 60 * 1000), preparingMessage: '...' });
    }
  }

  ngOnInit() {
    this.ganttChartView = <GanttChartView.Element>(<HTMLElement>this.ganttChartViewRef.nativeElement).firstChild;

    // Optionally, initialize custom themes (themes.js).
    initializeGanttChartTheme(this.settings, this.theme);
  }
}

<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content below * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * Delete the template below * * * * * * * * * * -->
<!-- * * * * * * * to get started with your project! * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

<style>
  :host {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    font-size: 14px;
    color: #333;
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    margin: 8px 0;
  }

  p {
    margin: 0;
  }

  .spacer {
    flex: 1;
  }

  .toolbar {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 60px;
    display: flex;
    align-items: center;
    background-color: #1976d2;
    color: white;
    font-weight: 600;
  }

  .toolbar img {
    margin: 0 16px;
  }

  .toolbar #twitter-logo {
    height: 40px;
    margin: 0 8px;
  }

  .toolbar #youtube-logo {
    height: 40px;
    margin: 0 16px;
  }

  .toolbar #twitter-logo:hover,
  .toolbar #youtube-logo:hover {
    opacity: 0.8;
  }

  .content {
    display: flex;
    margin: 82px auto 32px;
    padding: 0 16px;
    max-width: 960px;
    flex-direction: column;
    align-items: center;
  }

  svg.material-icons {
    height: 24px;
    width: auto;
  }

  svg.material-icons:not(:last-child) {
    margin-right: 8px;
  }

  .card svg.material-icons path {
    fill: #888;
  }

  .card-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    margin-top: 16px;
  }

  .card {
    all: unset;
    border-radius: 4px;
    border: 1px solid #eee;
    background-color: #fafafa;
    height: 40px;
    width: 200px;
    margin: 0 8px 16px;
    padding: 16px;
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    transition: all 0.2s ease-in-out;
    line-height: 24px;
  }

  .card-container .card:not(:last-child) {
    margin-right: 0;
  }

  .card.card-small {
    height: 16px;
    width: 168px;
  }

  .card-container .card:not(.highlight-card) {
    cursor: pointer;
  }

  .card-container .card:not(.highlight-card):hover {
    transform: translateY(-3px);
    box-shadow: 0 4px 17px rgba(0, 0, 0, 0.35);
  }

  .card-container .card:not(.highlight-card):hover .material-icons path {
    fill: rgb(105, 103, 103);
  }

  .card.highlight-card {
    background-color: #1976d2;
    color: white;
    font-weight: 600;
    border: none;
    width: auto;
    min-width: 30%;
    position: relative;
  }

  .card.card.highlight-card span {
    margin-left: 60px;
  }

  svg#rocket {
    width: 80px;
    position: absolute;
    left: -10px;
    top: -24px;
  }

  svg#rocket-smoke {
    height: calc(100vh - 95px);
    position: absolute;
    top: 10px;
    right: 180px;
    z-index: -10;
  }

  a,
  a:visited,
  a:hover {
    color: #1976d2;
    text-decoration: none;
  }

  a:hover {
    color: #125699;
  }

  .terminal {
    position: relative;
    width: 80%;
    max-width: 600px;
    border-radius: 6px;
    padding-top: 45px;
    margin-top: 8px;
    overflow: hidden;
    background-color: rgb(15, 15, 16);
  }

  .terminal::before {
    content: "\2022 \2022 \2022";
    position: absolute;
    top: 0;
    left: 0;
    height: 4px;
    background: rgb(58, 58, 58);
    color: #c2c3c4;
    width: 100%;
    font-size: 2rem;
    line-height: 0;
    padding: 14px 0;
    text-indent: 4px;
  }

  .terminal pre {
    font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
    color: white;
    padding: 0 1rem 1rem;
    margin: 0;
  }

  .circle-link {
    height: 40px;
    width: 40px;
    border-radius: 40px;
    margin: 8px;
    background-color: white;
    border: 1px solid #eeeeee;
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
    transition: 1s ease-out;
  }

  .circle-link:hover {
    transform: translateY(-0.25rem);
    box-shadow: 0px 3px 15px rgba(0, 0, 0, 0.2);
  }

  footer {
    margin-top: 8px;
    display: flex;
    align-items: center;
    line-height: 20px;
  }

  footer a {
    display: flex;
    align-items: center;
  }

  .github-star-badge {
    color: #24292e;
    display: flex;
    align-items: center;
    font-size: 12px;
    padding: 3px 10px;
    border: 1px solid rgba(27,31,35,.2);
    border-radius: 3px;
    background-image: linear-gradient(-180deg,#fafbfc,#eff3f6 90%);
    margin-left: 4px;
    font-weight: 600;
  }

  .github-star-badge:hover {
    background-image: linear-gradient(-180deg,#f0f3f6,#e6ebf1 90%);
    border-color: rgba(27,31,35,.35);
    background-position: -.5em;
  }

  .github-star-badge .material-icons {
    height: 16px;
    width: 16px;
    margin-right: 4px;
  }

  svg#clouds {
    position: fixed;
    bottom: -160px;
    left: -230px;
    z-index: -10;
    width: 1920px;
  }

  /* Responsive Styles */
  @media screen and (max-width: 767px) {
    .card-container > *:not(.circle-link) ,
    .terminal {
      width: 100%;
    }

    .card:not(.highlight-card) {
      height: 16px;
      margin: 8px 0;
    }

    .card.highlight-card span {
      margin-left: 72px;
    }

    svg#rocket-smoke {
      right: 120px;
      transform: rotate(-5deg);
    }
  }

  @media screen and (max-width: 575px) {
    svg#rocket-smoke {
      display: none;
      visibility: hidden;
    }
  }
</style>

<h1>GanttChartView sample</h1>
<div class="ribbonContainer">
  <div class="ribbonPanel">
    <div class="ribbonHeader">Items</div>
    <div class="ribbonCommandsArea">
      <div class="ribbonCommand"><a href="javascript://" (click)="addNewItem()" title="Add new item"><img src="assets/images/AddNew.png" alt="Add new" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="insertNewItem()" title="Insert new item before selection"><img src="assets/images/InsertNew.png" alt="Insert new" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="decreaseItemIndentation()" title="Decrease selected item indentation"><img src="assets/images/DecreaseIndentation.png" alt="Increase indentation" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="increaseItemIndentation()" title="Increase selected item indentation"><img src="assets/images/IncreaseIndentation.png" alt="Increase indentation" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="deleteItem()" title="Delete selected item"><img src="assets/images/Delete.png" alt="Delete selected item" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="setCustomBarColorToItem()" title="Set custom bar color to selected item"><img src="assets/images/SetColor.png" alt="Set color" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="copyItem()" title="Copy selected item"><img src="assets/images/Copy.png" alt="Copy" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="pasteItem()" title="Paste after selected item"><img src="assets/images/Paste.png" alt="Paste" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="moveItemUp()" title="Move selected item up"><img src="assets/images/MoveUp.png" alt="Move up" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="moveItemDown()" title="Move selected item down"><img src="assets/images/MoveDown.png" alt="Move down" /></a></div>
    </div>
  </div>
  <div class="ribbonPanel">
    <div class="ribbonHeader">Timeline/Schedule</div>
    <div class="ribbonCommandsArea">
      <div class="ribbonCommand"><a href="javascript://" (click)="setCustomScales()" title="Set custom scales"><img src="assets/images/CustomScales.png" alt="Custom scales" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="zoomIn()" title="Zoom in"><img src="assets/images/ZoomIn.png" alt="Zoom in" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="decreaseTimelinePage()" title="Move towards past"><img src="assets/images/DecreaseTimelinePage.png" alt="Decrease timeline page" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="increaseTimelinePage()" title="Move towards future"><img src="assets/images/IncreaseTimelinePage.png" alt="Increase timeline page" /></a></div>
    </div>
  </div>
  <div class="ribbonPanel">
    <div class="ribbonHeader">Project tools</div>
    <div class="ribbonCommandsArea">
      <div class="ribbonCommand toggle" [ngClass]="{'pressed': isBaselineVisible}"><a href="javascript://" (click)="toggleBaseline()" title="Hide/display baseline"><img src="assets/images/Baseline.png" alt="Baseline" /></a></div>
      <div class="ribbonCommand toggle" [ngClass]="{'pressed': isHighlightCriticalPathVisible}"><a href="javascript://" (click)="highlightCriticalPath()" title="Highlight/refresh critical path"><img src="assets/images/CriticalPath.png" alt="Critical path" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="splitRemainingWork()" title="Split work upon completion point in order to be able to reschedule remaining work separately"><img src="assets/images/SplitRemainingWork.png" alt="Split remaining work" /></a></div>
      <div class="ribbonCommand toggle pressed" [ngClass]="{'pressed': isDependencyConstraintsActive}"><a href="javascript://" (click)="toggleDependencyConstraints()" title="Disable/enable automatic scheduling"><img src="assets/images/DependencyConstraints.png" alt="Dependency constraints" /></a></div>
      <div class="ribbonCommand"><a href="javascript://" (click)="levelResources()" title="Level resources"><img src="assets/images/LevelResources.png" alt="Level resources" /></a></div>
    </div>
  </div>
  <div class="ribbonPanel">
    <div class="ribbonHeader">Printing</div>
    <div class="ribbonCommandsArea">
      <div class="ribbonCommand"><a href="javascript://" (click)="print()" title="Print"><img src="assets/images/Print.png" alt="Print" /></a></div>
    </div>
  </div>
</div>
<!-- Gantt Chart component. -->
<ganttchartview #ganttChartView [items]="items" [settings]="settings" [change]="onItemChanged" style="min-height: 388px">...</ganttchartview>

// GanttChartHyperLibraryDemos/Demos/Samples/React/GanttChartView/MainFeatures/app.jsx
var ganttChartView;
class App extends React.Component {
    constructor(props) {
        super(props);
        this.ganttChartViewRef = React.createRef();
    }
    componentDidMount() {
        ganttChartView = this.ganttChartViewRef.current;
    }
    render() {
        // Query string syntax: ?theme
        // Supported themes: Default, Generic-bright, Generic-blue, DlhSoft-gray, Purple-green, Steel-blue, Dark-black, Cyan-green, Blue-navy, Orange-brown, Teal-green, Purple-beige, Gray-blue, Aero.
        var queryString = window.location.search;
        var theme = queryString ? queryString.substr(1) : null;

        var date = new Date(), year = date.getFullYear(), month = date.getMonth();
        var items = [{ content: 'Task 1', isExpanded: false },
        { content: 'Task 1.1', indentation: 1, start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 4, 16, 0, 0) },
        { content: 'Task 1.2', indentation: 1, start: new Date(year, month, 3, 8, 0, 0), finish: new Date(year, month, 5, 12, 0, 0) },
        { content: 'Task 2', isExpanded: true },
        { content: 'Task 2.1', indentation: 1, start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 8, 16, 0, 0), completedFinish: new Date(year, month, 5, 16, 0, 0), assignmentsContent: 'Resource 1, Resource 2 [50%]' },
        { content: 'Task 2.2', indentation: 1 },
        { content: 'Task 2.2.1', indentation: 2, start: new Date(year, month, 11, 8, 0, 0), finish: new Date(year, month, 14, 16, 0, 0), completedFinish: new Date(year, month, 14, 16, 0, 0), assignmentsContent: 'Resource 2' },
        { content: 'Task 2.2.2', indentation: 2, start: new Date(year, month, 12, 12, 0, 0), finish: new Date(year, month, 14, 16, 0, 0), assignmentsContent: 'Resource 2' },
        { content: 'Task 3', indentation: 1, start: new Date(year, month, 15, 16, 0, 0), isMilestone: true }];
        items[3].predecessors = [{ item: items[0], dependencyType: 'SS' }];
        items[7].predecessors = [{ item: items[6], lag: 2 * 60 * 60 * 1000 }];
        items[8].predecessors = [{ item: items[4] }, { item: items[5] }];
        for (var i = 4; i <= 16; i++)
            items.push({ content: 'Task ' + i, indentation: i >= 8 && i % 3 == 2 ? 0 : 1, start: new Date(year, month, 2 + (i <= 8 ? (i - 4) * 3 : i - 8), 8, 0, 0), finish: new Date(year, month, 2 + (i <= 8 ? (i - 4) * 3 + (i > 8 ? 6 : 1) : i - 2), 16, 0, 0) });
        items[9].finish.setDate(items[9].finish.getDate() + 2);
        items[9].assignmentsContent = 'Resource 1';
        items[10].predecessors = [{ item: items[9] }];

        var settings = {
            // Auto-scheduling is initially turned on.
            areTaskDependencyConstraintsEnabled: true,
            // Set the current time value to automatically scroll to a specific chart coordinate, and display a vertical bar highlighter at the specified point.
            currentTime: new Date(year, month, 2, 12, 0, 0)
        };

        // Optionally, set baseline properties.
        items[6].baselineStart = new Date(year, month, 10, 8, 0, 0);
        items[6].baselineFinish = new Date(year, month, 11, 16, 0, 0);
        items[7].baselineStart = new Date(year, month, 8, 8, 0, 0);
        items[7].baselineFinish = new Date(year, month, 11, 16, 0, 0);
        items[8].baselineStart = new Date(year, month, 12, 8, 0, 0);

        // Customize columns.
        var columns = DlhSoft.Controls.GanttChartView.getDefaultColumns(items, settings);
        var indexOffset = columns[0].isSelection ? 1 : 0;
        columns.splice(0 + indexOffset, 0, { header: '', width: 40, cellTemplate: DlhSoft.Controls.GanttChartView.getIndexColumnTemplate() });
        columns.splice(3 + indexOffset, 0, { header: 'Effort (h)', width: 80, cellTemplate: DlhSoft.Controls.GanttChartView.getTotalEffortColumnTemplate(64) });
        columns.splice(4 + indexOffset, 0, { header: 'Duration (d)', width: 80, cellTemplate: DlhSoft.Controls.GanttChartView.getDurationColumnTemplate(64, 8) });
        columns.splice(8 + indexOffset, 0, { header: '%', width: 80, cellTemplate: DlhSoft.Controls.GanttChartView.getCompletionColumnTemplate(64) });
        columns.splice(9 + indexOffset, 0, { header: 'Predecessors', width: 100, cellTemplate: DlhSoft.Controls.GanttChartView.getPredecessorsColumnTemplate(84) });
        columns.push({ header: 'Cost ($)', width: 100, cellTemplate: DlhSoft.Controls.GanttChartView.getCostColumnTemplate(84) });
        columns.push({ header: 'Est. start', width: 140, cellTemplate: DlhSoft.Controls.GanttChartView.getBaselineStartColumnTemplate(124, true, true, 8 * 60 * 60 * 1000) }); // 8 AM
        columns.push({ header: 'Est. finish', width: 140, cellTemplate: DlhSoft.Controls.GanttChartView.getBaselineFinishColumnTemplate(124, true, true, 16 * 60 * 60 * 1000) }); // 4 PM
        settings.columns = columns;
        // Optionally, initialize custom themes (themes.js).
        initializeGanttChartTheme(settings, theme);
        function onItemChanged(item, propertyName, isDirect, isFinal) {
            if (!isDirect || !isFinal) // Skip internal changes, and changes occurred during drag operations.
                return;
            console.log(propertyName + ' changed for ' + item.content + '.');
        }
        function addNewItem() {
            var item = { content: 'New task', start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 4, 16, 0, 0) };
            ganttChartView.addItem(item);
            ganttChartView.selectItem(item);
            ganttChartView.scrollToItem(item);
            ganttChartView.scrollToDateTime(new Date(year, month, 1));
        }
        function insertNewItem() {
            if (ganttChartView.selectedItem == null)
                return;
            var item = { content: 'New task', start: new Date(year, month, 2, 8, 0, 0), finish: new Date(year, month, 4, 16, 0, 0) };
            ganttChartView.insertItem(ganttChartView.selectedItem.index, item);
            ganttChartView.selectItem(item);
            ganttChartView.scrollToItem(item);
            ganttChartView.scrollToDateTime(new Date(year, month, 1));
        }
        function increaseItemIndentation() {
            var item = ganttChartView.selectedItem;
            if (item == null)
                return;
            ganttChartView.increaseItemIndentation(item);
            ganttChartView.scrollToItem(item);
        }
        function decreaseItemIndentation() {
            var item = ganttChartView.selectedItem;
            if (item == null)
                return;
            ganttChartView.decreaseItemIndentation(item);
            ganttChartView.scrollToItem(item);
        }
        function deleteItem() {
            if (ganttChartView.selectedItem == null)
                return;
            ganttChartView.removeItem(ganttChartView.selectedItem, true); // Also remove successors' predecessor information.
        }
        function setCustomBarColorToItem() {
            if (ganttChartView.selectedItem == null)
                return;
            var item = ganttChartView.selectedItem;
            item.barStyle = 'stroke: Green; fill: LightGreen';
            item.completedBarStyle = 'stroke: Gray; fill: Gray';
            ganttChartView.refreshChartItem(item);
        }
        function copyItem() {
            if (ganttChartView.selectedItem == null)
                return;
            copiedItem = ganttChartView.selectedItem;
        }
        var copiedItem = null;
        function pasteItem() {
            if (copiedItem == null || ganttChartView.selectedItem == null)
                return;
            var item = { content: copiedItem.content, start: copiedItem.start, finish: copiedItem.finish, completedFinish: copiedItem.completedFinish, isMilestone: copiedItem.isMilestone, assignmentsContent: copiedItem.assignmentsContent, isRelativeToTimezone: copiedItem.isRelativeToTimezone };
            ganttChartView.insertItem(ganttChartView.selectedItem.index + 1, item);
            ganttChartView.selectItem(item);
            ganttChartView.scrollToItem(item);
            ganttChartView.scrollToDateTime(item.start);
        }
        function moveItemUp() {
            if (ganttChartView.selectedItem == null)
                return;
            var item = ganttChartView.selectedItem;
            ganttChartView.moveItemHierarchyUp(item);
            ganttChartView.scrollToItem(item);
        }
        function moveItemDown() {
            if (ganttChartView.selectedItem == null)
                return;
            var item = ganttChartView.selectedItem;
            ganttChartView.moveItemHierarchyDown(item);
            ganttChartView.scrollToItem(item);
        }
        function increaseTimelinePage() {
            ganttChartView.increaseTimelinePage(4 * 7 * 24 * 60 * 60 * 1000); // 4 weeks
        }
        function decreaseTimelinePage() {
            ganttChartView.decreaseTimelinePage(4 * 7 * 24 * 60 * 60 * 1000); // 4 weeks
        }
        function setCustomScales() {
            var settings = ganttChartView.settings;
            settings.headerHeight = 21 * 3;
            settings.scales = [{ scaleType: 'NonworkingTime', isHeaderVisible: false, isHighlightingVisible: true, highlightingStyle: 'stroke-width: 0; fill: #f8f8f8; fill-opacity: 0.65' },
            { scaleType: 'Months', headerTextFormat: 'Month', headerStyle: 'padding: 2.25px; border-right: solid 1px White; border-bottom: solid 1px White; color: gray; white-space: nowrap; overflow: hidden; text-overflow: ellipsis', isSeparatorVisible: true, separatorStyle: 'stroke: #c8bfe7; stroke-width: 0.5px' },
            { scaleType: 'Weeks', headerTextFormat: 'Date', headerStyle: 'padding: 2.25px; border-right: solid 1px White; border-bottom: solid 1px White; color: gray', isSeparatorVisible: true, separatorStyle: 'stroke: #c8bfe7; stroke-width: 0.5px' },
            { scaleType: 'Days', headerTextFormat: 'Day', headerStyle: 'padding: 2.25px; border-right: solid 1px White; color: gray' },
            { scaleType: 'CurrentTime', isHeaderVisible: false, isSeparatorVisible: true, separatorStyle: 'stroke: #e31d3b; stroke-width: 0.5px' }];
            settings.updateScale = 60 * 60 * 1000; // 1 hour
            settings.hourWidth = 5;
            settings.visibleWeekStart = 1; // Monday
            settings.visibleWeekFinish = 5; // Friday
            settings.workingWeekStart = 1; // Monday
            settings.workingWeekFinish = 4; // Thursday
            settings.visibleDayStart = 10 * 60 * 60 * 1000; // 10 AM
            settings.visibleDayFinish = 20 * 60 * 60 * 1000; // 8 PM
            settings.specialNonworkingDays = [new Date(year, month, 24), new Date(year, month, 25)];
            ganttChartView.refresh();
        }
        function zoomIn() {
            var settings = ganttChartView.settings;
            ganttChartView.setHourWidth(settings.hourWidth * 2);
        }
        function toggleBaseline() {
            var settings = ganttChartView.settings;
            settings.isBaselineVisible = !settings.isBaselineVisible;
            toggleBaselineCommand.className = settings.isBaselineVisible ? 'ribbonCommand toggle pressed' : 'ribbonCommand toggle';
            ganttChartView.refresh();
        }
        function highlightCriticalPath() {
            highlightCriticalPathCommand.className = 'ribbonCommand toggle pressed';
            for (var i = 0; i < ganttChartView.items.length; i++) {
                var item = ganttChartView.items[i];
                delete item.barStyle;
                if (!item.hasChildren && ganttChartView.isItemCritical(item))
                    item.barStyle = 'stroke: #e31d3b; fill: #e31d3b';
                ganttChartView.refreshChartItem(item);
            }
        }
        function splitRemainingWork() {
            if (ganttChartView.selectedItem == null)
                return;
            var remainingWorkItem = ganttChartView.splitRemainingWork(ganttChartView.selectedItem, ' (rem. work)', ' (compl. work)');
            if (remainingWorkItem == null)
                return;
            ganttChartView.scrollToItem(remainingWorkItem);
        }
        function toggleDependencyConstraints() {
            var settings = ganttChartView.settings;
            settings.areTaskDependencyConstraintsEnabled = !settings.areTaskDependencyConstraintsEnabled;
            toggleDependencyConstraintsCommand.className = settings.areTaskDependencyConstraintsEnabled ? 'ribbonCommand toggle pressed' : 'ribbonCommand toggle';
            ganttChartView.refresh();
        }
        function levelResources() {
            // Level the assigned resources for all tasks, including the already started ones, considering the current time displayed in the chart.
            ganttChartView.levelResources(true, ganttChartView.settings.currentTime);
            // Alternatively, optimize work to obtain the minimum project finish date and time assuming unlimited resource availability:
            // ganttChartView.optimizeWork(false, true, ganttChartView.settings.currentTime);
        }
        function print() {
            // Print the task hierarchy column and a selected timeline page of 5 weeks (timeline end week extensions would be added automatically, if necessary).
            // Optionally, to rotate the print output and simulate Landscape printing mode (when the end user keeps Portrait selection in the Print dialog), append the rotate parameter set to true to the method call: rotate: true.
            ganttChartView.print({ title: 'Gantt Chart (printable)', isGridVisible: true, columnIndexes: [1], timelineStart: new Date(year, month, 1), timelineFinish: new Date(new Date(year, month, 1).valueOf() + 5 * 7 * 24 * 60 * 60 * 1000), preparingMessage: '...' });
        }
        return (
            <div>
                <div className="ribbonContainer">
                    <div className="ribbonPanel">
                        <div className="ribbonHeader">Items</div>
                        <div className="ribbonCommandsArea">
                            <div className="ribbonCommand"><a href="#" onClick={addNewItem} title="Add new item"><img src="Images/AddNew.png" alt="Add new" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={insertNewItem} title="Insert new item before selection"><img src="Images/InsertNew.png" alt="Insert new" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={decreaseItemIndentation} title="Decrease selected item indentation"><img src="Images/DecreaseIndentation.png" alt="Increase indentation" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={increaseItemIndentation} title="Increase selected item indentation"><img src="Images/IncreaseIndentation.png" alt="Increase indentation" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={deleteItem} title="Delete selected item"><img src="Images/Delete.png" alt="Delete selected item" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={setCustomBarColorToItem} title="Set custom bar color to selected item"><img src="Images/SetColor.png" alt="Set color" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={copyItem} title="Copy selected item"><img src="Images/Copy.png" alt="Copy" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={pasteItem} title="Paste after selected item"><img src="Images/Paste.png" alt="Paste" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={moveItemUp} title="Move selected item up"><img src="Images/MoveUp.png" alt="Move up" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={moveItemDown} title="Move selected item down"><img src="Images/MoveDown.png" alt="Move down" /></a></div>
                        </div>
                    </div>
                    <div className="ribbonPanel">
                        <div className="ribbonHeader">Timeline/Schedule</div>
                        <div className="ribbonCommandsArea">
                            <div className="ribbonCommand"><a href="#" onClick={setCustomScales} title="Set custom scales"><img src="Images/CustomScales.png" alt="Custom scales" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={zoomIn} title="Zoom in"><img src="Images/ZoomIn.png" alt="Zoom in" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={decreaseTimelinePage} title="Move towards past"><img src="Images/DecreaseTimelinePage.png" alt="Decrease timeline page" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={increaseTimelinePage} title="Move towards future"><img src="Images/IncreaseTimelinePage.png" alt="Increase timeline page" /></a></div>
                        </div>
                    </div>
                    <div className="ribbonPanel">
                        <div className="ribbonHeader">Project tools</div>
                        <div className="ribbonCommandsArea">
                            <div className="ribbonCommand toggle pressed" id="toggleBaselineCommand"><a href="#" onClick={toggleBaseline} title="Hide/display baseline"><img src="Images/Baseline.png" alt="Baseline" /></a></div>
                            <div className="ribbonCommand toggle" id="highlightCriticalPathCommand"><a href="#" onClick={highlightCriticalPath} title="Highlight/refresh critical path"><img src="Images/CriticalPath.png" alt="Critical path" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={splitRemainingWork} title="Split work upon completion point in order to be able to reschedule remaining work separately"><img src="Images/SplitRemainingWork.png" alt="Split remaining work" /></a></div>
                            <div className="ribbonCommand toggle pressed" id="toggleDependencyConstraintsCommand"><a href="#" onClick={toggleDependencyConstraints} title="Disable/enable automatic scheduling"><img src="Images/DependencyConstraints.png" alt="Dependency constraints" /></a></div>
                            <div className="ribbonCommand"><a href="#" onClick={levelResources} title="Level resources"><img src="Images/LevelResources.png" alt="Level resources" /></a></div>
                        </div>
                    </div>
                    <div className="ribbonPanel">
                        <div className="ribbonHeader">Printing</div>
                        <div className="ribbonCommandsArea">
                            <div className="ribbonCommand"><a href="#" onClick={print} title="Print"><img src="Images/Print.png" alt="Print" /></a></div>
                        </div>
                    </div>
                </div>
                <GanttChartView ref={this.ganttChartViewRef} items={items} settings={settings} change={onItemChanged} style={{ minHeight: '388px' }}>...</GanttChartView>
            </div>);
    }
}
